### DISCUSSION TITLE
CouchDB binds port 80 making impossible to install nginx proxy manager for reverse proxy

### DISCUSSION THREAD

**Discussion by fillipp97** [vrtmrz/obsidian-livesync#519] [General]
Dear all,

I recently got to know livesync and I tried to configure it. I almost managed to do it. However when configuring Nginx Proxy Manager as a proxy I get errors while building the docker compose since port 80 is already in use by couchDB.

How can I make the two apps co-exist in my raspberry pi?
Thank you in advance!

**Comment by SamBouwer** [comment]
Can you share  your docker compose setup, if you are using that? I suspect you are binding port 80 of your couchdb container to port 80 on your host (your raspberry pi). You should be able to bind another free port on your host to port 80 of your couchdb container. In docker compose it would be similar to this:

Note the syntax of the line with "port:" and the line below it

```
version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:80"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=YOURPASSWORD
    volumes:
        - ./dbdata:/opt/couchdb/data
```

Example snippet taken from https://gist.github.com/hamzamu/2c2a12c36f132acfb130278fc0f5ccf0#file-docker-compose-yml
