### DISCUSSION TITLE
Quartz integration/hosting as a website

### DISCUSSION THREAD

**Discussion by Maritsu** [vrtmrz/obsidian-livesync#616] [Q&A]
Is there an existing solution for running LiveSync and serving a web version of the vault (e.g. using [Quartz](https://github.com/jackyzha0/quartz)) on the same server? If not, would there be a way to create such a thing?

**Comment by EricChen1248** [comment]
Hey, so I was browsing through discussions to see if anyone came up with a better solution for this, but doesn't seem like one. I do already have a setup for this working, but it's kinda jank

I first setup a obsidian instance using linuxserver.io

```
---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-package-install 
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=zh_CN.UTF-8
    volumes:
      - ./config:/config
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    shm_size: "256m"
    restart: unless-stopped
    networks:
      - public_net
```
Start off with the ports uncommented, then go visit localhost:3000 (or I have it running on my server, so server:3000), and you get the familiar obsidian interface. Setup the obsidian live sync as you would for a normal local version. (My vault is named "Obsidian Vault" in my examples) (I then comment out the ports so they don't take up a port spot, I use Caddy for most of my reverse proxying needs)

Then for quartz, I just run this compose file
```
services:
  quartz:
    build: .
    restart: unless-stopped
    # command: npx quartz build
    volumes:
      - ../obsidian-server/config/Obsidian Vault:/usr/src/app/content
      - ./public:/usr/src/app/public
  quartz_nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/quartz/public:ro
    networks:
      - public_net
networks:
  public_net:
    external: true
```


The jankiest part I think is the linuxserver.io image to install the livesync plugin and sync it. If there was a cli tool that could connect to the couchdb instance and dump the files directly to the filesystem, it would make this very production ready.
