### ISSUE TITLE
Syncing does not create files and entryies on other devices

### ISSUE THREAD

**Issue by derpieler** [vrtmrz/obsidian-livesync#139]
I've been trying to set up my sync again for days. At some point there was a point when new documents were not created on the other devices. I now have 3 devices (2 PC and 1 iPhone) with 3 different versions. How do I get this synced again. I use Couchdb. Currently still in the local network. Should I create a new DB and start over completely once? What would be the procedure? Discard on all devices and use the setup wizard on one device and transfer the ID on the other devices? I strongly assume that the one PC contains a complete data set.
I thank you for any hints and support.

**Comment by vrtmrz** [comment]
Thank you for asking me!
Are any messages shown on some devices?

As you said, the easiest way is to rebuild everything from the `Setting` dialogue. the procedure is below.

1. Press the `Rebuild` button in the `Remote Database Configuration` pane from the most established device.
2. Then automatically the remote database getting being rebuilt. And all other devices will be locked out temporarily in their first synchronising after remote database rebuilding.
3. From each other device, press the `Fetch` button of `Fetch rebuilt DB` in the `Local Database Configuration` pane. The lock will be unlocked.

**Comment by Cityjohn** [comment]
> 

This solution does not work. I've had the same issue many times and this never works. What's even worse is that when I go into the CouchDB Fauxton utility I very clearly can not even find most of my local files in it after I have rebuilt the remote database. My only solution to date has been to restart the couchDB server. could it be that having a non persistence docker image may break livesync when a server interupt happens?

**Comment by xinput** [comment]
i seem to have the same problem and can't seem to solve it. 

Sync is running and also the log sais that it's writing files to the DB, but the notes and the installed plugins does not appear to be synced to my iOS client.

tried the above mentioned steps which did not seem to work.  Also th Fauxton DB that I created seems to be pretty empty. I'm not that experienced in couchdb though, so can't tell that for sure.

Any ideas?

**Comment by vrtmrz** [comment]
Thank you for your information! 
Had no document synchronised? Or also plugins? 

And may I have your configuration report that was made by the Make report button on the Hatch pane of the settings dialogue?

**Comment by xinput** [comment]
Thanks for the quick reply.
Yes, both - notes and plugins are not synchronized.

here‘s the report from my iOS client. Let me know if you also need the one from my primary desktop client.

<details>
  <summary>show report</summary>

```
----remote config----
uuids:
  algorithm: sequential
  max_count: "1000"
cluster:
  n: "3"
  q: "2"
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  backlog: "512"
  bind_address: any
  max_db_number_for_dbs_info_req: "100"
  max_http_request_size: "4294967296"
  port: "5984"
  prefer_minimal: Cache-Control, Content-Length, Content-Range, Content-Type,
    ETag, Server, Transfer-Encoding, Vary
  require_valid_user: "true"
  server_options: "[{recbuf, undefined}]"
  socket_options: "[{sndbuf, 262144}, {nodelay, true}]"
attachments:
  compressible_types: text/*, application/javascript, application/json, application/xml
  compression_level: "8"
admins: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
query_server_config:
  os_process_limit: "100"
  reduce_limit: "true"
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  require_valid_user: "true"
replicator:
  connection_timeout: "30000"
  http_connections: "20"
  interval: "60000"
  max_churn: "20"
  max_jobs: "500"
  retries_per_request: "5"
  socket_options: "[{keepalive, true}, {nodelay, false}]"
  ssl_certificate_max_depth: "3"
  startup_jitter: "5000"
  verify_ssl_certificates: "false"
  worker_batch_size: "500"
  worker_processes: "4"
ssl:
  port: "6984"
log:
  level: info
  writer: stderr
indexers:
  couch_mrview: "true"
couch_peruser:
  database_prefix: userdb-
  delete_dbs: "false"
  enable: "false"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  allow_jsonp: "false"
  authentication_handlers: "{couch_httpd_auth, cookie_authentication_handler},
    {couch_httpd_auth, default_authentication_handler}"
  bind_address: 127.0.0.1
  enable_cors: "true"
  enable_xframe_options: "false"
  max_http_request_size: "4294967296"
  port: "5986"
  secure_rewrites: "true"
  socket_options: "[{sndbuf, 262144}]"
ioq.bypass:
  compaction: "false"
  os_process: "true"
  read: "true"
  shard_sync: "false"
  view_update: "true"
  write: "true"
ioq:
  concurrency: "10"
  ratio: "0.01"
couch_httpd_auth:
  allow_persistent_cookies: "true"
  auth_cache_size: "50"
  authentication_db: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  authentication_redirect: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  iterations: "10"
  require_valid_user: "false"
  timeout: "600"
  secret: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  attachment_stream_buffer_size: "4096"
  changes_doc_ids_optimization_threshold: "100"
  database_dir: ./data
  default_engine: couch
  default_security: admin_only
  file_compression: snappy
  max_dbs_open: "500"
  max_document_size: "50000000"
  os_process_timeout: "5000"
  single_node: "true"
  users_db_security_editable: "false"
  uuid: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_PASSWORD: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_DBNAME: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
liveSync: false
syncOnSave: true
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: true
passphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
doNotDeleteFolder: false
resolveConflictsByNewerFile: true
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: true
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 17
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: true
configPassphraseStore: ""
encryptedPassphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
encryptedCouchDBConnection: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
```
</details>
