### ISSUE TITLE
Plugin icons are not showing in Linux

### ISSUE THREAD

**Issue by mhdali** [vrtmrz/obsidian-livesync#143]
![2022-11-20_01:12](https://user-images.githubusercontent.com/6121579/202863206-87f2166a-0a23-4c78-8882-bfa4cfa3afe6.jpg)

Even the sync icons are not showing (which is annoying to know if the sync has been finished or not). 
![2022-11-20_01:16:47](https://user-images.githubusercontent.com/6121579/202863289-5d51db06-c9e1-4a60-9f73-1d5a0b3e8181.jpg)

I'm using Archlinux and I tried to install icon packages to resolve this issue, nothing works. 

Thanks for your help.

**Comment by vrtmrz** [comment]
Thank you for asking me and apologies for the delay!

All icons have been rendered in emojis.
So we have to install fonts which have emojis.

Alternatively, we can use Google Fonts (If we would not be worried about an internet connection) by following CSS snippets.

```css
@import url('https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&display=swap');

label.sls-setting-label,
.CodeMirror-wrap::before,
.cm-s-obsidian>.cm-editor::before {
    font-family: 'Noto Color Emoji', sans-serif;
}
```
