### ISSUE TITLE
CouchDB setup: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### ISSUE THREAD

**Issue by arminus** [vrtmrz/obsidian-livesync#17]
So I've tried to set up CouchDB with a Caddy proxy and a LetsEncrypt cert, below's the docker compose. Access to Fauxton on the given address works, however, testing the connection from the plugin throws this error (my.domain.tld is actually ${COUCHDB_SERVER} as configured for Docker):

Access to fetch at 'https://my.domain.tld//' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Any ideas?

```
version: "3.7"

services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/caddy:/data

  couchserver:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PW}
    volumes:
        - ./data/couchdb:/opt/couchdb/data
    networks:
      - caddy
    labels:
      caddy: ${COUCHDB_SERVER}
      caddy.header.Access-Control-Allow-Origin: "app://obsidian.md"
      caddy.header.Access-Control-Allow-Methods: "\"GET, POST, PATCH, PUT, DELETE, OPTIONS\""
      caddy.header.Access-Control-Allow-Credentials: "true"
      caddy.header.Access-Control-Allow-Headers: "Origin, Content-Type"
      caddy.header.-Server: ""
      caddy.reverse_proxy: "{{upstreams 5984}}"

  # https://stackoverflow.com/questions/63623075/how-to-run-commands-from-docker-compose-yml-to-start-couchdb
  initializer:
    image: curlimages/curl
    depends_on:
      - couchserver
    command: ["sh","-c","sleep 15 && curl -u ${COUCHDB_USER}:${COUCHDB_PW} -X PUT couchserver:5984/_users &&  curl -u ${COUCHDB_USER}:${COUCHDB_PW} -X PUT couchserver:5984/test"]
    networks:
      - caddy
```
