### ISSUE TITLE
Setup Difficulties - Remote database is newer or corrupted make sure to latest version of self-hosted-livesync installed

### ISSUE THREAD

**Issue by LaserKaspar** [vrtmrz/obsidian-livesync#175]
Hi, I recently found this project and would like to try it out, but sadly I can't connect a second instance to it. I get the following error message: ``Remote database is newer or corrupted make sure to latest version of self-hosted-livesync installed``

![image](https://user-images.githubusercontent.com/30759364/219178050-223c9d7f-f7ba-498a-b577-b55ddda649b0.png)

This is my local.ini file. 
```
[cors]
credentials=true
headers=accept, authorization, content-type, origin, referer
max_age=3600
methods=GET, PUT, POST, HEAD, DELETE
origins=app://obsidian.md,capacitor://localhost,http://localhost,http://192.168.68.110,http://192.168.68.110:5984

[chttpd]
bind_address=any
max_http_request_size=4294967296
port=5984
require_valid_user=true

[admins]
admin=<you probably don't need this>

[vendor]
name=The Apache Software Foundation

[feature_flags]
partitioned||*=true

[chttpd_auth]
authentication_redirect=/_utils/session.html
hash_algorithms=sha256, sha
require_valid_user=true

[indexers]
couch_mrview=true

[prometheus]
additional_port=false
bind_address=127.0.0.1
port=17986

[httpd]
WWW-Authenticate="\"Basic realm=\\\"couchdb\\\"\""
bind_address=127.0.0.1
enable_cors=true
port=5986

[smoosh]
state_dir=./data

[couch_httpd_auth]
authentication_db=_users

[couchdb_engines]
couch=couch_bt_engine

[couchdb]
database_dir=./data
max_document_size=50000000
single_node=true
uuid=3370b91172243a8b62491ed619898d0d
view_index_dir=./data
```

I installed it via docker and I am using the following compose:
```
version: '3.3'
services:
    couchdb:
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password
        volumes:
            - './local.ini:/opt/couchdb/etc/local.ini'
        ports:
            - '5984:5984'
        image: couchdb
        
        # http://192.168.68.110:5984
```

I hope you can help, I would love to try this project!
