### ISSUE TITLE
The plugin won’t work for me, keep getting sync errors 

### ISSUE THREAD

**Issue by BobWs** [vrtmrz/obsidian-livesync#215]
So I have tried your plugin, but unfortunately it doesn’t work for me. I keep getting sync errors when adding my second device (ios ipad)
Here is a summary of the steps that I took:

- installed obsidian desktop on my macbook
- setup everything with a local vault on the mac
- imported my notes from joplin
- installed and setup the docker couchdb
- checked and tested the database connection with a sub.domain (everything works)
- installed your plugin and followed the wizard steps and the reamdme
- checked and tested the sync connection and the database check all was marked okay
- next installed obsidian on my ipad and setup with a new local vault
- installed the plugin on the ipad
- copied over the open url as mentioned in the readme
- the pugin started to do its thing and then I keep getting sync errors
  only one folder was downloaded from the database after that I couldn’t get it to work anymore and keep getting errors on both devices (desktop and ipad)

 Any idea how to solve this issue?

 TIA

**Comment by vrtmrz** [comment]
I apologise that being so late!

I think that the steps you have taken are correct, and I am also wondering why it has not synchronised.
Would you mind please check is something shown on the log? We can see that by clicking the document box icon on the Ribbon.

**Comment by BobWs** [comment]
> I apologise that being so late!
> 
> I think that the steps you have taken are correct, and I am also wondering why it has not synchronised. Would you mind please check is something shown on the log? We can see that by clicking the document box icon on the Ribbon.

Thank you for replying, but unfortunately I have moved on with another sync plugin. At the moment I’m using the [Remotely Safe plugin](https://github.com/remotely-save/remotely-save).
This is working out of box without any problems for me.

**Comment by vrtmrz** [comment]
I see. I will miss you, but I am so glad that you have found it more convenient for you.
I hope to thank you once again for your trying!

**Comment by BobWs** [comment]
I will try your plugin again soon. But for me two things are very important and they are;
- multi-user support
- and stable usage and synchronization on multiple devices

If your plugin can support this in a simple way in the near future I will definitely consider using it. 
Especially since Remotely Save is not really maintained anymore.

**Comment by vrtmrz** [comment]
Welcome back!
> multi-user support

Does this mean that each fully privileged user shares a single CouchDB server?
If so, this possibly could be achieved by using a customised reverse proxy. (As you probably know, the best is to use a dedicated server for each).
As nginx configuration, I wrote it in [another discussion](https://github.com/vrtmrz/obsidian-livesync/issues/210#issuecomment-1554199778). I hope that this helps us,

> and stable usage and synchronization on multiple devices

I really hope so. If you don't mind, could you give me a detailed log or something? I have recently written some materials about that. 
The following materials would be help for us with trouble:
- [Plug-in log](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging)
- [Information on DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools)
- [Configuration report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report)

**Comment by BobWs** [comment]
So I decided to try your plugin on more time, but the problem is still the same. I keep getting replication error and it would sync properly. 
See my logs:
```
27/05/2023, 19:17:59->loading plugin
27/05/2023, 19:17:59->Self-hosted LiveSync v0.19.5 0.19.5 
27/05/2023, 19:17:59->Waiting for ready...
27/05/2023, 19:17:59->Opening Database...
27/05/2023, 19:17:59->Database is now ready.
27/05/2023, 19:17:59->Initialize and checking database files
27/05/2023, 19:17:59->Checking deleted files
27/05/2023, 19:18:00->Updating database by new files
27/05/2023, 19:18:00->UPDATE DATABASE
27/05/2023, 19:18:00->UPDATE DATABASE done.
27/05/2023, 19:18:00->UPDATE STORAGE
27/05/2023, 19:18:00->UPDATE STORAGE done.
27/05/2023, 19:18:01->CHECK FILE STATUS:357/457
27/05/2023, 19:18:01->CHECK FILE STATUS:357/457 done.
27/05/2023, 19:18:01->CHECK FILE STATUS:257/457
27/05/2023, 19:18:01->CHECK FILE STATUS:257/457 done.
27/05/2023, 19:18:01->CHECK FILE STATUS:157/457
27/05/2023, 19:18:01->CHECK FILE STATUS:157/457 done.
27/05/2023, 19:18:01->CHECK FILE STATUS:57/457
27/05/2023, 19:18:01->CHECK FILE STATUS:57/457 done.
27/05/2023, 19:18:01->CHECK FILE STATUS:0/457
27/05/2023, 19:18:01->CHECK FILE STATUS:0/457 done.
27/05/2023, 19:18:01->Initialized, NOW TRACKING!
27/05/2023, 19:18:01->OneShot Sync begin... (sync)
27/05/2023, 19:18:05->TypeError:Failed to fetch
27/05/2023, 19:18:05->Replication error
27/05/2023, 19:18:05->Error:Failed to fetch
27/05/2023, 19:18:05->Replication stopped.
27/05/2023, 19:18:05->Replication error
27/05/2023, 19:18:05->Error:Failed to fetch
```

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /e=_/_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 19
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 250
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: true
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: false
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
```
If you could find some time to help me figure out what the problem is, I would much appreciate it!
