### ISSUE TITLE
Syncing works from desktop, but error connecting to DB from iPhone.  Same Wifi network.

### ISSUE THREAD

**Issue by hiro5id** [vrtmrz/obsidian-livesync#267]
## Abstract
Syncing works from desktop, but error connecting to DB from iPhone.  Same Wifi network.  The error on iPhone when clicking "Test" during setup.  And syncing of course dos not work on iPHone.

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Everything synchronised

## Actually happened
- When configuring Sync on iPhone, clicking "Test" results in: error: "could not connect to https://obsidian-sync.noobtech.com: the_database (TypeError:Lod failed)"
- No files synchronised
- Synhronization works fine on Desktop MacOS with the same configuration no problems. iPhone is on the sane WIFI network as the working MacOS.

## Reproducing procedure

1. Configure LiveSync as in the attached material.
2. Click the test button
3. Get error: "could not connect to https://obsidian-sync.noobtech.com: the_database (TypeError:Lod failed)"
4. Synchronization cannot begin.

### Report from the LiveSync
<details>
<summary>Report from hatch</summary>

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET,PUT,POST,HEAD,DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 0.0.0.0
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  secret: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  authentication_redirect: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_PASSWORD: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_DBNAME: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 19
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
encryptedCouchDBConnection: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore

```
</details>

### Screenshots
If applicable, please add screenshots to help explain your problem.

![image](https://github.com/vrtmrz/obsidian-livesync/assets/3152718/c6e64dd2-c2d2-4d98-9665-46d555c35361)
