### ISSUE TITLE
Can't resolve "Some files have been left conflicted", Files Don't Exist

### ISSUE THREAD

**Issue by jwreford** [vrtmrz/obsidian-livesync#274]
## Abstract
Each device says 'Some files have been left conflicted. Please resolve them by "Pick a file to resolve conflict". The list is written in the log.
However files do not exist on any of my 3 devices, and there is no dialog box to resolve the conflict.

Everything was working fine for me until earlier today. I had made lots of changes to my vault on one device, and when I opened another device I choose to 'Do later' the conflict resolution. After this I couldn't get the dialog box back to resolve the conflicts, so I manually corrected each device's vault. 

## Expected behaviour
These files don't exist, so they shouldn't be conflicted.
Also, I should see a dialog box that I can choose an option to resolve the conflict.

## Actually happened
There is no dialog box so the message appears each time I start Obsidian on any device.

## Reproducing procedure
Open Obsidian, and wait for the notification message to appear.
It happens consistently, every time.

Note: If you do not catch the reproducing procedure, please let me know the frequency and signs.

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET,PUT,POST,HEAD,DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 0.0.0.0
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: true
autoSweepPlugins: true
autoSweepPluginsPeriodic: true
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 19
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore

```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
29/08/2023, 21:33:41->All files enumerated
29/08/2023, 21:33:41->Additional safety scan..
29/08/2023, 21:33:41->Before LiveSync, start OneShot once...
29/08/2023, 21:33:41->OneShot Sync begin... (pullOnly)
29/08/2023, 21:33:41->Some files have been left conflicted! Please resolve them by "Pick a file to resolve conflict". The list is written in the log.
29/08/2023, 21:33:41->Conflicted: 3D Printing/GCode.md
29/08/2023, 21:33:41->Conflicted: 3D Printing/GCode.md.edtz
29/08/2023, 21:33:41->Conflicted: Day Planners/Day Planner-20230827.md
29/08/2023, 21:33:41->Conflicted: Day Planners/Day Planner-20230829.md
29/08/2023, 21:33:41->Conflicted: Untitled.md
29/08/2023, 21:33:41->Conflicted: Untitled.md.edtz
29/08/2023, 21:33:41->Conflicted: Work/Adobe.md
29/08/2023, 21:33:41->Conflicted: Work/Email.md
29/08/2023, 21:33:41->Conflicted: Work/<Redacted>.md
29/08/2023, 21:33:41->Additional safety scan done
29/08/2023, 21:33:41->All files enumerated
29/08/2023, 21:33:42->Replication activated
29/08/2023, 21:33:42->Replication paused
29/08/2023, 21:33:42->Replication completed
29/08/2023, 21:33:42->LiveSync begin...
29/08/2023, 21:33:42->Replication activated
29/08/2023, 21:33:42->Replication paused
29/08/2023, 21:33:42->Replication activated
```
</details>

Let me know if there is any other information or logs you need. Thanks so much for creating this plugin!
