### ISSUE TITLE
Daily note doesnt sync to primary device, deletes previously written content and syncs deletion back to secondary device

### ISSUE THREAD

**Issue by Outlet2048** [vrtmrz/obsidian-livesync#303]
Thank you for taking the time to report this issue!
To improve the process, I would like to ask you to let me know the information in advance.

All instructions and examples, and empty entries can be deleted.
Just for your information, a [filled example](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Issue+example) is also written.

## Abstract
Livesync eats my daily note when it has been created from phone first

## Expected behaviour
- Sync begins on Desktop after note has been modified on mobile
- Desktop creates daily note as well from template while sync begins
- Sync ends and merges the text from mobile into template
- Note: this has worked fine for quite some time

## Actually happened
- Desktop creates file from template
- Sync error (see log)
- Empty daily note from template is synced back from desktop to mobile, deleting all my work

## Reproducing procedure

Note: If you do not catch the reproducing procedure, please let me know the frequency and signs.
-> Happens whenever I begin writing a daily note from phone and desktop gets it later

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Logs</summary>

```
10/13/2023, 8:18:28 PM->loading plugin
10/13/2023, 8:18:28 PM->Self-hosted LiveSync v0.20.2 0.20.2 
10/13/2023, 8:18:28 PM->Self-hosted LiveSync has undergone a major upgrade. Please open the setting dialog, and check the information pane.
10/13/2023, 8:18:28 PM->Waiting for ready...
10/13/2023, 8:18:29 PM->Opening Database...
10/13/2023, 8:18:29 PM->Database is now ready.
10/13/2023, 8:18:31 PM->Initialize and checking database files
10/13/2023, 8:18:31 PM->Checking deleted files
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 25
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 50
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 75
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 100
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 125
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 150
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 175
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 200
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 225
10/13/2023, 8:18:32 PM->Collecting local files on the DB: 250
10/13/2023, 8:18:32 PM->Updating database by new files
10/13/2023, 8:18:32 PM->UPDATE DATABASE
10/13/2023, 8:18:32 PM->UPDATE DATABASE: PASS:0, FAILED:0
10/13/2023, 8:18:32 PM->UPDATE STORAGE
10/13/2023, 8:18:32 PM->UPDATE STORAGE: PASS:98, FAILED:0
10/13/2023, 8:18:32 PM->CHECK FILE STATUS:2/2
10/13/2023, 8:18:32 PM->CHECK FILE STATUS:2/2: PASS:71, FAILED:0
10/13/2023, 8:18:33 PM->CHECK FILE STATUS:1/2
10/13/2023, 8:18:33 PM->CHECK FILE STATUS:1/2: PASS:100, FAILED:0
10/13/2023, 8:18:33 PM->Initialized, NOW TRACKING!
10/13/2023, 8:18:33 PM->Before LiveSync, start OneShot once...
10/13/2023, 8:18:33 PM->OneShot Sync begin... (pullOnly)
10/13/2023, 8:18:33 PM->Replication activated
10/13/2023, 8:18:34 PM->Replication completed
10/13/2023, 8:18:34 PM->LiveSync begin...
10/13/2023, 8:18:34 PM->Replication activated
10/13/2023, 8:18:34 PM->DB -> STORAGE (modify,plain) Daily Notes/2023/10/2023-10-12-Thursday.md
10/13/2023, 8:18:34 PM->Applied Daily Notes/2023/10/2023-10-12-Thursday.md (f:9ee5368d85f57f371b43acd6939d58451e59dcf8ff4393140a033fafacbd3d75:62-ff2ff209c07f48acbaa5c446ff2699d9) change...
10/13/2023, 8:18:34 PM->Delete: Daily Notes/2023/10/2023-10-12-Thursday.md: Conflict revision has been deleted and resolved
10/13/2023, 8:18:34 PM->DB -> STORAGE (modify,force,plain) Daily Notes/2023/10/2023-10-12-Thursday.md
10/13/2023, 8:18:34 PM->Applied Daily Notes/2023/10/2023-10-12-Thursday.md (f:9ee5368d85f57f371b43acd6939d58451e59dcf8ff4393140a033fafacbd3d75:2-1886f600461f9b90b09f6c46603b0be4) change...
10/13/2023, 8:18:35 PM->Delete: !-To-Do.md: Conflict revision has been deleted and resolved
10/13/2023, 8:18:35 PM->Content saved:Daily Notes/2023/10/2023-10-13-Friday.md ,chunks: 2 (new:0, skip:3, cache:1)
10/13/2023, 8:18:35 PM->DB -> STORAGE (modify,plain) Events and Activities.md
10/13/2023, 8:18:35 PM->Applied Events and Activities.md (f:e32c65dfd2271860b3f9deb04e42e2231826e2a7b0d74c8d8cd2e65095e89f5a:206-d7f53a3112de4c2c8ed0a147484b944e) change...
10/13/2023, 8:18:35 PM->DB -> STORAGE (modify,plain) !-To-Do.md
10/13/2023, 8:18:35 PM->DB -> STORAGE (modify,force,plain) !-To-Do.md
10/13/2023, 8:18:35 PM->DB <- STORAGE (plain) Daily Notes/2023/10/2023-10-13-Friday.md
10/13/2023, 8:18:35 PM->DB -> STORAGE (create,plain) ERROR, Could not write: Daily Notes/2023/10/2023-10-13-Friday.md
10/13/2023, 8:18:35 PM->Applied Daily Notes/2023/10/2023-10-13-Friday.md (f:eb67351c619f00e3de4a9e7d38eea18a72e4192a3fd5a894ba2c8831e39dabb0:2-dc8b1a54f9744ae9846ebd7b03366065) change...
10/13/2023, 8:18:46 PM->Replication closed
10/13/2023, 8:18:47 PM->AbortError:The user aborted a request.
10/13/2023, 8:18:48 PM->Before LiveSync, start OneShot once...
10/13/2023, 8:18:48 PM->OneShot Sync begin... (pullOnly)
10/13/2023, 8:18:48 PM->Replication activated
10/13/2023, 8:18:48 PM->Replication completed
10/13/2023, 8:18:48 PM->LiveSync begin...
10/13/2023, 8:18:50 PM->Replication closed
10/13/2023, 8:18:51 PM->AbortError:The user aborted a request.
10/13/2023, 8:22:41 PM->Before LiveSync, start OneShot once...
10/13/2023, 8:22:41 PM->OneShot Sync begin... (pullOnly)
10/13/2023, 8:22:41 PM->Replication completed
10/13/2023, 8:22:41 PM->LiveSync begin...
10/13/2023, 8:23:10 PM->Replication closed
10/13/2023, 8:23:11 PM->AbortError:The user aborted a request.
10/13/2023, 8:39:28 PM->Before LiveSync, start OneShot once...
10/13/2023, 8:39:28 PM->OneShot Sync begin... (pullOnly)
10/13/2023, 8:39:28 PM->Replication completed
10/13/2023, 8:39:28 PM->LiveSync begin...
```
</details>

### Other information, insights and intuition.
Thanks for creating livesync :)

**Comment by vrtmrz** [comment]
Thank you for your report and detailed information!
It has been so helpful! Without this, we could not know that the reason has been caused by write fail.
However, I am still not sure why writing to the storage had failed. Would you please enable the `Verbose log` and check what has actually happened? The `Verbose log` could be enabled on the `General Settings` pane.

> Thanks for creating livesync :)

We are creating it! I appreciate you for your patience and contribution! I hope to make it better with all together!

**Comment by vrtmrz** [comment]
Thank you for your detailed reproducing procedure!
Thanks for it, the issue has been reproduced!

It should happen with all new notes created during boot.
I will address it later!

**Comment by alexgorbatchev** [comment]
Also seeing this on 0.23, using windows, macos and android

cc @Outlet2048 

verbose log from windows instance:

```
6/28/2024, 10:05:32 AM->Check or pull from db:Projects/archive/van/General tips.md OK
6/28/2024, 10:05:32 AM->UPDATE STORAGE: DONE:10, FAILED:0, LAST:14
6/28/2024, 10:05:32 AM->STORAGE <- DB (create,plain) ERROR, Could not write: Projects/archive/van/Parts.md
6/28/2024, 10:05:32 AM->Error:File already exists.
6/28/2024, 10:05:32 AM->Check or pull from db:Projects/archive/van/Parts.md OK
6/28/2024, 10:05:32 AM->STORAGE <- DB (create,plain) ERROR, Could not write: Projects/archive/van/References.md
6/28/2024, 10:05:32 AM->Error:File already exists.
6/28/2024, 10:05:32 AM->Check or pull from db:Projects/archive/van/References.md OK
6/28/2024, 10:05:32 AM->STORAGE <- DB (create,plain) ERROR, Could not write: Projects/archive/van/Roof.md
6/28/2024, 10:05:32 AM->Error:File already exists.
6/28/2024, 10:05:32 AM->Check or pull from db:Projects/archive/van/Roof.md OK
6/28/2024, 10:05:32 AM->STORAGE <- DB (create,plain) ERROR, Could not write: Projects/archive/van/Seats.md
6/28/2024, 10:05:32 AM->Error:File already exists.
6/28/2024, 10:05:32 AM->Check or pull from db:Projects/archive/van/Seats.md OK
6/28/2024, 10:05:32 AM->STORAGE <- DB (create,plain) ERROR, Could not write: Projects/archive/van/Security.md
6/28/2024, 10:05:32 AM->Error:File already exists.
```

here's my config file if that helps

```yaml
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: ***************
couchDB_DBNAME: obsidian
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 2d991095cb9bf88e
ignoreVersionCheck: false
lastReadUpdates: 23
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: live-sync.config.md
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 0
enableCompression: false
accessKey: ""
bucket: ""
endpoint: ""
region: auto
secretKey: ""
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
```
