### ISSUE TITLE
livesyncを0.20.4にアップデートしてから、Obsidianが再起動したり同期がうまく行きません

### ISSUE THREAD

**Issue by Piorimu** [vrtmrz/obsidian-livesync#305]
## Abstract
livesyncを0.20.4にアップデートしてから、iPhoneで起動中にObsidianが再起動することがあります。
iPhone12でiOSバージョンは16.6.1で、Obsidianバージョンは1.4.16です。

また、同期に失敗することが多くなりました。

## Expected behaviour
- 同期はメッセージで終了しますReplication completed
- すべてが同期されています

## Actually happened
- 起動時の全ファイル走査（UPDATE DATABASE）中に再起動が発生します。
- アップデート以前のファイルの更新が同期されません。
- v2データベースにRebuildした後でも同様です。
- またv1データベースにRebuildし直しても発生しました。

- コンフリクト解消時にも再起動が発生しました。

## Reproducing procedure

1.iPhoneでObisidianを起動します。
2.ログを開きます（Show log）
3.しばらくすると再起動することがあります。
4.再起動後もLiveSyncを有効にしていても、ファイルの同期が行われません。
5.何度かObsidianを再起動すると同期することがあります。
6.iPhone側で文字を入力しても再起動が発生することがあります。

### Report from the LiveSync
<details>
<summary>Report from hatch</summary>

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /e=_/_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  secret: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  authentication_redirect: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  view_index_dir: ./data

---- Plug-in config ---
version:0.20.4
couchDB_URI: self-hosted
couchDB_USER: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_PASSWORD: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_DBNAME: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: false
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 20
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: obsidian
ignoreVersionCheck: false
lastReadUpdates: 20
deleteMetadataOfDeletedFiles: true
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 10
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
encryptedCouchDBConnection: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: true
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
useV1: true
```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
SYSTEM INFO:
	Operating system: ios 16.6.1 (Apple iPhone)
	Obsidian version: 1.4.16 (114)
	API version: v1.4.16
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Self-hosted LiveSync v0.20.4

```
</details>

### Plug-in log
再起動を繰り返すため、保存できませんでした。
一部スクリーンショットしたので参照ください。

### Screenshots
![image](https://github.com/vrtmrz/obsidian-livesync/assets/2674144/d482a244-f0e3-4b67-b9a4-b9b6df3980df)
![image](https://github.com/vrtmrz/obsidian-livesync/assets/2674144/17cca855-487f-4053-b642-3020813c3eca)

### Other information, insights and intuition.
サーバーホスティングサービスはFly.ioです（VMはv2、shared-cpu-1x | 1 shared | 256MB）
同期しているVaultは2,492files、ローカルディスク上でのサイズは325MBです。
