### ISSUE TITLE
Error on parsing fly.toml , deploy_couchdb_to_flyio_v2_with_swap.ipynb  

### ISSUE THREAD

**Issue by potatochick2020** [vrtmrz/obsidian-livesync#310]
## Abstract
The script is not working 
```
Error: failed loading app config from /home/ec2-user/obsidian-livesync/fly.toml: toml: line 28: Key 'build' has already been defined.
```
I had use the following command to run `deploy_couchdb_to_flyio_v2_with_swap.ipynb `
```bash
sudo ipython --TerminalIPythonApp.file_to_run= deploy_couchdb_to_flyio_v2_with_swap.ipynb
```
Generated fly.toml,
```toml
# fly.toml app configuration file generated for purple-sound-5047 on 2023-10-25T02:42:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purple-sound-5047"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 5984
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  COUCHDB_USER = "alkcsa93"

ERL_FLAGS="-couch_ini /opt/couchdb/etc/default.ini /opt/couchdb/etc/default.d/ /opt/couchdb/etc/local.d /opt/couchdb/etc/local.ini /opt/couchdb/data/persistence.ini"

[mounts]
  source="couchdata"
  destination="/opt/couchdb/data"

[build]
  dockerfile = "./Dockerfile"
```

System:
```
AWS linux
```

Date of running the script : `25/10/2023`

May I know can you reproduce the issue by simply running the colab notebook, if yes, may I try to edit the notebook to fix the issue and submit a pull request. Thanks.
