### ISSUE TITLE
Help me! Fly.io Volume Usage 100%. 1. Sync is not possible. 2. Perform cleaning is failed.

### ISSUE THREAD

**Issue by dlphnkck** [vrtmrz/obsidian-livesync#312]
I am upset, so I apologize if my writing is clumsy.

## Abstract

1. 2GB volume of Fly.io's CouchDB is almost 100% used and cannot be synchronized.
	- Local file size is about 200MB.
	- The number of notes is about 7,000. 
2. Perform cleaning is failed. 
3. Is there no other way but to run Rebuild everything?
    I've done this many times before, but it takes several hours and I don't really want to do it 😅.

## Expected behaviour
The local Obsidian file size is 200MB, so I hope it will be reduced to that size.

## Actually happened
1. Volume Usage on Fly.io has increased from 823MB to 1.93GiB in the last month, but since Fly.io only has records for the last 30 days, I do not know how fast it increased before that.
2. I ran the Perfom cleanup on Fly.io's remote databases, but the process seems to have failed and the disk usage has not decreased.

## Reproducing procedure
I tried Perform cleaning on Remote databases (and Local databases) from the Maintain tab, but it failed.

```log
2023/10/27 hh:mm:ss->Cleaning remote database
2023/10/27 hh:mm:ss->Database active-size: 955 MB, external-size:896 MB, file-size: 1 GB
2023/10/27 hh:mm:ss->Collecting unreferenced chunks on 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
2023/10/27 hh:mm:ss->Lock remote database to prevent data corruption
2023/10/27 hh:mm:ss->Failed to make design document for operating chunks
2023/10/27 hh:mm:ss->{
  "error": "error",
  "reason": "internal_server_error",
  "status": 500,
  "name": "error",
  "message": "internal_server_error",
  "stack": "Error\n    at generateErrorFromResponse (plugin:obsidian-livesync:4670:35)\n    at fetchJSON (plugin:obsidian-livesync:9623:13)\n    at async HttpPouch.o._put (plugin:obsidian-livesync:9916:16)",
  "docId": "_design/chunks"
}
2023/10/27 hh:mm:ss->Could not prepare design document for operating chunks
2023/10/27 hh:mm:ss->No unreferenced chunks! 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
2023/10/27 hh:mm:ss->Compacting database...
2023/10/27 hh:mm:ss->Compacting database done
2023/10/27 hh:mm:ss->Processed database active-size: 955 MB, external-size:896 MB, file-size: 1 GB
2023/10/27 hh:mm:ss->Reduced sizes: active-size: -, external-size:-, file-size: -
2023/10/27 hh:mm:ss->Cleaning remote database up: Done
2023/10/27 hh:mm:ss->Cleaning local database
2023/10/27 hh:mm:ss->Collecting unreferenced chunks on 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷-livesync-v2
```

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync

<details>
<summary>remote config</summary>
```
----remote config----
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data
```
</details>

<details>
<summary>Plug-in config</summary>
```
---- Plug-in config ---
version:0.20.6
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: false
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: true
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 19
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: false
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
useV1: false
workingUseDynamicIterationCount: false
```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.3
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 18
		1: Calendar v1.5.10
		2: Commander v0.5.1
		3: Excalidraw v1.9.26
		4: Outliner v4.8.0
		5: Plugin Update Tracker v1.5.2
		6: ReadItLater v0.3.1
		7: Self-hosted LiveSync v0.20.6
		8: Templater v1.16.4
		9: Various Complements v9.0.1
		10: Vimrc Support v0.9.0
		11: Search on Internet v0.5.0
		12: Toggl Track v0.11.0
		13: 2Hop Links Plus v0.37.0
		14: Advanced URI v1.38.1
		15: Version History Diff v2.1.9
		16: Editing Toolbar v2.3.1
		17: QuickAdd v1.4.0
		18: Word Splitting for Simplified Chinese in Edit Mode and Vim Mode v1.10.0
```
</details>

### Plug-in log

Sorry, I didn't know where the "Document box icon" was.

### Network log
```
Failed to load resource: the server responded with a status of 500 ()
```
```
POST https://𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷.fly.dev/𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷/_bulk_docs 500
fetch @ plugin:obsidian-livesync:22087
ourFetch @ plugin:obsidian-livesync:9600
fetchJSON @ plugin:obsidian-livesync:9616
HttpPouch.o._bulkDocs @ plugin:obsidian-livesync:9904
await in HttpPouch.o._bulkDocs (async)
eval @ plugin:obsidian-livesync:6861
eval @ plugin:obsidian-livesync:4926
eval @ plugin:obsidian-livesync:4890
eval @ plugin:obsidian-livesync:4883
bulkDocs @ plugin:obsidian-livesync:1931
```
### Screenshots
Chart of Volume Usage in Fly.io.
![2023-10-27 Fly io Volume Usage Chart](https://github.com/vrtmrz/obsidian-livesync/assets/117900337/766f42d3-3324-470a-a77f-4c5577e1c988)

### Other information, insights and intuition.
That is all.
The questions are,

1. Why has Fly.io's Volume Usage increased so dramatically in the last 30 days alone?
2. How to reduce this kind of Volume Usage.

That is all.

I apologize for the length of this article.
I was upset, so I know there is a lot of material missing .
Please feel free to ask.

Thanks for reading.

**Comment by dlphnkck** [comment]
Sorry.

1. Report from the LiveSync
2. Obsidian debug info 

I'll reformat it and repost them.


## Report materials
### Report from the LiveSync

<details>
<summary>remote config</summary>

```
----remote config----
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data
```
</details>

<details>
<summary>Plug-in config</summary>

```
---- Plug-in config ---
version:0.20.6
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: false
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: true
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 19
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: false
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
useV1: false
workingUseDynamicIterationCount: false
```
</details>

### Obsidian debug info

<details>
<summary>Debug info</summary>

```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.3
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 18
		1: Calendar v1.5.10
		2: Commander v0.5.1
		3: Excalidraw v1.9.26
		4: Outliner v4.8.0
		5: Plugin Update Tracker v1.5.2
		6: ReadItLater v0.3.1
		7: Self-hosted LiveSync v0.20.6
		8: Templater v1.16.4
		9: Various Complements v9.0.1
		10: Vimrc Support v0.9.0
		11: Search on Internet v0.5.0
		12: Toggl Track v0.11.0
		13: 2Hop Links Plus v0.37.0
		14: Advanced URI v1.38.1
		15: Version History Diff v2.1.9
		16: Editing Toolbar v2.3.1
		17: QuickAdd v1.4.0
		18: Word Splitting for Simplified Chinese in Edit Mode and Vim Mode v1.10.0
		
RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
</details>
