### ISSUE TITLE
Data from couchDB comes in base64 format

### ISSUE THREAD

**Issue by talkenson** [vrtmrz/obsidian-livesync#337]
## Abstract
When setting up secondary device, data returned from server is base64 encoded
So it's very unusable on mobile

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Every note opens in natural text, not the base64 encoded format

## Actually happened
- Synchronisation ends with the message `Replication completed`
- Every note appears in the base64 encoded format

## Reproducing procedure

1. Configure LiveSync's second device
2. Wait until end
3. Restart (also it's optional) obsidian
4. Open any note

Note: It fixes by itself when I'm updating via livesync preset, with file opened

### Report from the LiveSync

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET,PUT,POST,HEAD,DELETE
  origins: app://obsidian.md, capacitor://localhost, http://localhost
chttpd:
  bind_address: any
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 0.0.0.0
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.21.1
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: true
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
Home vault:11/25/2023, 6:07:50 PM->Replication closed
Home vault:11/25/2023, 6:07:51 PM->Scanning hidden files.
Home vault:11/25/2023, 6:07:51 PM->Hidden files scanned: 1 files had been modified
Home vault:11/25/2023, 6:07:51 PM->Before LiveSync, start OneShot once...
Home vault:11/25/2023, 6:07:51 PM->OneShot Sync begin... (pullOnly)
Home vault:11/25/2023, 6:07:51 PM->Replication activated
Home vault:11/25/2023, 6:07:51 PM->Replication completed
Home vault:11/25/2023, 6:07:51 PM->LiveSync begin...
Home vault:11/25/2023, 6:07:52 PM->Content saved:.obsidian/workspace-mobile.json ,chunks: 1 (new:1, skip:0, cache:0)
Home vault:11/25/2023, 6:07:52 PM->Replication activated
Home vault:11/25/2023, 6:07:52 PM->STORAGE --> DB:.obsidian/workspace-mobile.json: (hidden) Done
Home vault:11/25/2023, 6:07:54 PM->Content saved:.obsidian/workspace-mobile.json ,chunks: 1 (new:1, skip:0, cache:0)
Home vault:11/25/2023, 6:07:54 PM->Replication activated
Home vault:11/25/2023, 6:07:54 PM->STORAGE --> DB:.obsidian/workspace-mobile.json: (hidden) Done
```
</details>

It is okay

### Screenshots
![telegram-cloud-photo-size-2-5409136895994221200-y](https://github.com/vrtmrz/obsidian-livesync/assets/24260024/11928e43-3275-424f-8cd8-c9de51b0ee9c)
