### ISSUE TITLE
iphone decrption failed

### ISSUE THREAD

**Issue by cheng3969** [vrtmrz/obsidian-livesync#354]
Hi,
Im using ios 17.1.2, and got this issue, could you please help?
Thank you!

## Abstract
cant sync on iphone

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Everything synchronised

## Actually happened
- "Error:Encrypted data corrupted!"  
- Decryption failed
## Reproducing procedure

1. Configure LiveSync on 2 pcs, both works fine
2. Open setup url on iphone, nothing happens
3. set up iphone manually, and get above error.

### Report from the LiveSync
<details>
<summary>Report from hatch</summary>

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
ssl:
  cert_file: /etc/couchdb/cert/cert.pem
  enable: "true"
  key_file: /etc/couchdb/cert/key.pem
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  secret: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  authentication_redirect: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
  view_index_dir: ./data

---- Plug-in config ---
version:0.19.23
couchDB_URI: self-hosted
couchDB_USER: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_PASSWORD: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
couchDB_DBNAME: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 19
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
encryptedCouchDBConnection: "𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷"
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}

```
</details>
