### ISSUE TITLE
Sync occasionally hangs, and takes a long time to recover

### ISSUE THREAD

**Issue by zedtools** [vrtmrz/obsidian-livesync#382]
## Abstract
Sync occasionally seems to hang on one or more devices, but then recovers after a long time

## Expected behaviour
- If a device was recently synced, opening the app should sync the device and bring it up to date within a few seconds

## Actually happened
- Most of the time this works as expected, but occasionally it seems to hang. After hanging, if I leave Obsidian open long enough, it eventually recovers and continues syncing.
- It seems to take about 10-15 minutes to recover as long as Obsidian stays open.
- On iOS, when the screen goes to sleep, iOS seems to background the app and the sync starts again when I reopen it. I need to keep the screen away with Obsidian open for it to recover.

## Reproducing procedure

1. I have couchdb running on a QNAP NAS with Docker.
2. I have multiple clients syncing to the same server (Windows PC, MacBook, iPhone, iPad).
3. All clients occasionally exhibit this behaviour, and they have always recovered if I left Obsidian open and running long enough.

Note: If you do not catch the reproducing procedure, please let me know the frequency and signs.

### Report from the LiveSync

For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /obsidian-zain-baft/_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.20.7
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 20
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
useV1: false
```
</details>

### Plug-in log
Here is an example from my MacBook.

<details>
<summary>Plug-in log</summary>

```
15/02/2024, 17:06:50->Before LiveSync, start OneShot once...
15/02/2024, 17:06:50->OneShot Sync begin... (pullOnly)
15/02/2024, 17:06:54->Content saved:.obsidian/workspace.json ,chunks: 1 (new:1, skip:0, cache:0)
15/02/2024, 17:06:54->STORAGE --> DB:.obsidian/workspace.json: (hidden) Done
15/02/2024, 17:07:46->Content saved:.obsidian/workspace.json ,chunks: 1 (new:1, skip:0, cache:0)
15/02/2024, 17:07:46->STORAGE --> DB:.obsidian/workspace.json: (hidden) Done
15/02/2024, 17:07:50->Scanning hidden files.
15/02/2024, 17:07:50->Hidden files scanned: 1 files had been modified
15/02/2024, 17:07:53->Content saved:.obsidian/workspace.json ,chunks: 1 (new:1, skip:0, cache:0)
15/02/2024, 17:07:53->STORAGE --> DB:.obsidian/workspace.json: (hidden) Done
15/02/2024, 17:07:57->Content saved:.obsidian/workspace.json ,chunks: 1 (new:1, skip:0, cache:0)
15/02/2024, 17:07:57->STORAGE --> DB:.obsidian/workspace.json: (hidden) Done
15/02/2024, 17:08:00->Content saved:Test 2.md ,chunks: 11 (new:0, skip:21, cache:10)
15/02/2024, 17:08:00->DB <- STORAGE (plain) Test 2.md
15/02/2024, 17:08:50->Scanning hidden files.
15/02/2024, 17:08:50->Hidden files scanned: 1 files had been modified
15/02/2024, 17:09:50->Scanning hidden files.
15/02/2024, 17:09:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:10:50->Scanning hidden files.
15/02/2024, 17:10:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:11:50->Scanning hidden files.
15/02/2024, 17:11:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:11:58->Replication activated
15/02/2024, 17:12:50->Scanning hidden files.
15/02/2024, 17:12:50->Hidden files scanned: 1 files had been modified
15/02/2024, 17:13:50->Scanning hidden files.
15/02/2024, 17:13:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:14:50->Scanning hidden files.
15/02/2024, 17:14:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:15:50->Scanning hidden files.
15/02/2024, 17:15:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:16:50->Scanning hidden files.
15/02/2024, 17:16:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:17:50->Scanning hidden files.
15/02/2024, 17:17:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:18:50->Scanning hidden files.
15/02/2024, 17:18:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:19:50->Scanning hidden files.
15/02/2024, 17:19:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:21:50->Scanning hidden files.
15/02/2024, 17:21:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:22:50->Scanning hidden files.
15/02/2024, 17:22:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:23:50->Scanning hidden files.
15/02/2024, 17:23:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:24:50->Scanning hidden files.
15/02/2024, 17:24:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:25:50->Scanning hidden files.
15/02/2024, 17:25:50->Hidden files scanned: 0 files had been modified
15/02/2024, 17:26:12->Applied 1. Projects/xxxxxx/Untitled.md (1. Projects/xxxxxx/Untitled.md:14-f6fc2951aa0a415287c532337147f1af) change...
15/02/2024, 17:26:12->Replication completed
15/02/2024, 17:26:12->LiveSync begin...
15/02/2024, 17:26:13->DB -> STORAGE (create,plain) 1. Projects/xxxxxx/xxxxxx.md
15/02/2024, 17:26:13->Applied 1. Projects/xxxxxx/xxxxxx.md (1. Projects/xxxxxx/xxxxxx.md:7-88cf3bdd075c4b0ab8f10e8d361b85a6) change...
15/02/2024, 17:26:13->Replication activated
15/02/2024, 17:26:13->Applying hidden 3 files change...
15/02/2024, 17:26:13->Scanning hidden files.
15/02/2024, 17:26:13->Delete: 1. Projects/xxxxxx/yyyyyy.md: Conflict revision has been deleted and resolved
15/02/2024, 17:26:13->DB -> STORAGE (modify,plain) 1. Projects/xxxxxx/yyyyyy.md
15/02/2024, 17:26:13->DB -> STORAGE (modify,force,plain) 1. Projects/xxxxxx/yyyyyy.md
15/02/2024, 17:26:13->Hidden files scanned: 3 files had been modified
15/02/2024, 17:26:13->Applying hidden 3 files changed
15/02/2024, 17:26:14->Content saved:.obsidian/workspace.json ,chunks: 1 (new:1, skip:0, cache:0)
15/02/2024, 17:26:14->STORAGE --> DB:.obsidian/workspace.json: (hidden) Done
```
</details>

### Other information, insights and intuition.
This seems to affect the devices at around the same time. If one device is affected, the next time I open another device, it is likely to be in this stuck state. I have not determined if this happens every time, though. I also don't know what triggers it.

I also have a large vault (1630 files, 131 folders), and the most recent time this was happening (in the logs above), I noticed my QNAP CPU usage was hovering around 95% the entire time Obsidian was stuck. Once it recovered, the QNAP CPU usage dropped to around 50-70%.

I understand the QNAP has a weak CPU, and I have quite a lot of other processes running on it. I suspect the server is the bottleneck, but it still seems to take an unreasonably long time to recover.

Once it recovers, the sync happens quickly (within a few seconds). Interestingly, if I wait for one client to recover, that works fine while another is hung. For example, if I wait for my PC and Mac to recover, those two can sync data between them (within seconds). If I open Obsidian on my iPad, the QNAP CPU spikes and the iPad just sits there waiting for a sync, but the PC and Mac are still fine.
