### ISSUE TITLE
Renaming or deleting notes cause sync to be stuck, showing ⏳ Working read storage processes and/or 🛫 Pending read storage processes

### ISSUE THREAD

**Issue by jluo98** [vrtmrz/obsidian-livesync#399]
Thanks for your hard work on this community plugin! 

## Abstract
Renaming operations are stuck. 
Status displays `⏳1`. 
Synchronization would only complete when I restart Obsidian. 

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Everything synchronised

## Actually happened
- Newly renamed files are not synced until restart. 

## Reproducing procedure

1. Create a new note `Untitled` on primary device
2. Rename the note to `New Test File`
3. Status shows `⏳ 1`
4. Replicate on a secondary device
5. Only `Untitled` shows up
6. Restart Obsidian on primary device
7. `⏳` disappears, `New Test File` shows up on secondary device after replication

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.11 Chrome/120.0.6099.283 Electron/28.2.3 Safari/537.36
---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.22.16
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: true
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: false
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$,\/workspace-mobile.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 50c8117af5fe0fe7
ignoreVersionCheck: false
lastReadUpdates: 22
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: true
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: true
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 0
```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.11
	Operating system: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000 23.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Self-hosted LiveSync v0.22.16
		2: Enhancing Export v1.10.4

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
4/1/2024, 1:06:06 PM->Cache initialized 300 / 250000000000
4/1/2024, 1:06:06 PM->loading plugin
4/1/2024, 1:06:06 PM->Self-hosted LiveSync v0.22.16 0.22.16 
4/1/2024, 1:06:06 PM->xxhash for plugin initialised
4/1/2024, 1:06:06 PM->Waiting for ready...
4/1/2024, 1:06:06 PM->Opening Database...
4/1/2024, 1:06:06 PM->Database is now ready.
4/1/2024, 1:06:06 PM->Log window opened
4/1/2024, 1:06:06 PM->Initialize and checking database files
4/1/2024, 1:06:06 PM->Checking deleted files
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 25
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 50
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 75
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 100
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 125
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 150
4/1/2024, 1:06:06 PM->Collecting local files on the DB: 175
4/1/2024, 1:06:06 PM->Updating database by new files
4/1/2024, 1:06:06 PM->UPDATE DATABASE: Nothing to do
4/1/2024, 1:06:06 PM->UPDATE STORAGE
4/1/2024, 1:06:06 PM->UPDATE STORAGE All done: DONE:8, FAILED:0
4/1/2024, 1:06:06 PM->Initialized, NOW TRACKING!
4/1/2024, 1:06:06 PM->OneShot Sync begin... (sync)
4/1/2024, 1:06:06 PM->Replication activated
4/1/2024, 1:06:07 PM->Replication completed
4/1/2024, 1:06:18 PM->Chunks saved: doc: Untitled.md ,chunks: 1 (new:0, recycled:1, cached:0)
4/1/2024, 1:06:18 PM->STORAGE -> DB (plain) Untitled.md
4/1/2024, 1:06:18 PM->OneShot Sync begin... (sync)
4/1/2024, 1:06:19 PM->Replication activated
4/1/2024, 1:06:19 PM->Replication is already in progress.
4/1/2024, 1:06:19 PM->Replication completed
4/1/2024, 1:06:24 PM->OneShot Sync begin... (sync)
4/1/2024, 1:06:24 PM->Replication completed
4/1/2024, 1:06:24 PM->Entry removed:Untitled.md (f:f848af-13-1fe925855449427eb5fc8854547ebb4c)
4/1/2024, 1:06:24 PM->STORAGE -> DB (plain) New Test File.md
```
</details>

### Other information, insights and intuition.
Please provide any additional context or information about the problem.
