### ISSUE TITLE
FileWatching STORAGE -> DB (plain) updated leads to lag and duplicated characters on mobile devices like iPad

### ISSUE THREAD

**Issue by czenk** [vrtmrz/obsidian-livesync#401]
## Abstract
Local updates to PouchDB cause a lag to Obsidian each time.
Whilst this is barely noticeable on a PC, on e.g. an iPad this leads to unresponsiveness of the application and duplication of characters entered at the moment DB writes kick in - in my case to an extend that renders livesync unsuitable for note updates from my (6th gen) iPad.
I tried to disable all sync (via the command "Toggle All Sync") but this option only seems to affect replication between PouchDB and CouchDB, not chunk collection from local store into the local PouchDB. I failed to identify a way to suspend this process, even when all replication is suspended.

## Expected behaviour
- Filewatching/Writes to local PouchDB should not impact user experience (lag/responsiveness)
- Filewatching/Writes to local PouchDB should not impact the usability of the application (duplication of characters entered)
- Plugin activity should be minimised to what is actually needed to enable the synchronisation capability. In a use case other than "LiveSync" I'd assume there is no need for constant FileWatching for as long as no replication event is triggered. I'd assume there is only a need to keep the local DB up-to-date with local storage right before a synchronisation takes place (but pls. do correct me in case I am wrong here).

## Actually happened
- Updates to local PouchDB take place even with synchronisation disabled
- Increasing the Batch size in settings seems to redruce the number of updates, yet not to an extend that would remedy the impact on user experience and usability
- Activating "suspendFileWatching" remedies the issue, but in line with the purpose of this parameter, renders the replication capability of the plugin partially defunct

## Reproducing procedure

1. Configure LiveSync as in the attached material - all automated replication off.
2. Use a Pen input device on an iPad to update an existing note to experience the full impact (duplicated letters & lag - size of vault ca. 2200 notes).
3. To verify the cause for 2. watch plugin notifications "STORAGE -> DB", than activate "Suspend FileWatching" to verify the usability issues disappear.

## Report materials
N.A.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.13 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36
---- remote config ----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET,PUT,POST,HEAD,DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 0.0.0.0
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.22.16
couchDB_URI: self-hosted(HTTP)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: true
resolveConflictsByNewerFile: false
batchSave: true
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/,\/workspace$ ,\/workspace.json$,\/workspace-mobile.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 38e762a543fe78f5
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
N.A.
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
N.A.
```
</details>

### Network log
N.A.

### Screenshots
If applicable, please add screenshots to help explain your problem.

### Other information, insights and intuition.
Suggestion:
a) For all replication methods other than LiveSync, suspend FileWatching until a replication is triggered.
a) Only update the local PouchDB when an actual replication is triggered, rigth before the actual synchronisation with the remote DB takes place ... or - in case this impeeds some other use cases/capabilities of the plugin ...
b) Provide (a) configuration option(s) to manage the behaviour of local database operations, so that the behaviour suggested in a) (no local updates until a replication is about to start) can be configured

Apologies in advance if I just failed to understand how to properly configure livesync for my use case.
Please do not hesitate to reach out for any related queries - or in case you'd like support with documentation.

Thank you
