### ISSUE TITLE
memory leakage

### ISSUE THREAD

**Issue by IsidoreSong** [vrtmrz/obsidian-livesync#445]
## Abstract
After update to the newest version, I suffers memory leakage everytime when rebuild, fetch, scan local file at lauch on my 32 G memory laptop.

## Expected behaviour

- build local DB
- upload and download file smoothly (maybe slow)

## Actually happened

For 0.23.11 without toggle
![image](https://github.com/vrtmrz/obsidian-livesync/assets/51397898/5bfcddb1-5ccd-4fbc-a1bf-aef53df9f260)

0.23.11 with toggle
![image](https://github.com/vrtmrz/obsidian-livesync/assets/51397898/e786e5f0-5296-4688-ab1a-e394fc944e9a)

0.22
![image](https://github.com/vrtmrz/obsidian-livesync/assets/51397898/5f66b906-661b-4ac3-ae43-9fa3d4e588b9)

The memory would up and down serveral rounds and rocket to the limit and stun Obsidian.
~~After I toggle `Do not split chunks in the foreground`, it's done, everything is OK.~~

BTW, this default function should be running a new process in the **background**, right? Toggle `Do not split chunks in the **foreground**` is ...

## Reproducing procedure

1. Maybe just start a new sync on a 600 file vault?
2. The platform is not important, as only in the local DB building process it leaks.

---- Personal info ----
At first I was new to this plugin and started my exploring. Then it successfully connect my laptop and phone.
As there were some mismatch of the files, configs, I started a rebuild after the update of plugin.
I failed to smoothly sync and tweak the number in the config, like memory XXX, enhance XXX (no desp here, I don't know what it is).
I fetch, rebuild, back to non-configured, but it didn't help.
~~After I toggle `Do not split chunks in the foreground`, there is no more leakage and rebuild is also successfule.~~

### log

```
024/6/2 12:32:41->UPDATE DATABASE
2024/6/2 12:32:41->UPDATE STORAGE: Nothing to do
2024/6/2 12:32:46->Chunks saved: doc: 金刚经和道德经到底哪个更实用？ - 知乎.md ,chunks: 124 (new:124, recycled:0, cached:0)
2024/6/2 12:32:46->Chunks saved: doc: Oracle云服务器.md ,chunks: 34 (new:30, recycled:0, cached:4)
2024/6/2 12:32:46->STORAGE -> DB (plain) 金刚经和道德经到底哪个更实用？ - 知乎.md
2024/6/2 12:32:46->STORAGE -> DB (plain) Oracle云服务器.md
2024/6/2 12:32:46->Chunks saved: doc: python.md ,chunks: 18 (new:17, recycled:0, cached:1)
2024/6/2 12:32:46->Chunks saved: doc: tmp2.json ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:32:46->Chunks saved: doc: pages/Unsupervised Label Noise Modeling and Loss Correction.md ,chunks: 2 (new:2, recycled:0, cached:0)
2024/6/2 12:32:46->Chunks saved: doc: pages/Toward robustness against label noise in training deep discriminative neural networks.md ,chunks: 2 (new:2, recycled:0, cached:0)
2024/6/2 12:32:46->Chunks saved: doc: pages/Hybrid attention-based prototypical networks for noisy few-shot relation classification.md ,chunks: 13 (new:13, recycled:0, cached:0)
2024/6/2 12:32:46->Chunks saved: doc: Machine Configuration.canvas ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:32:47->Chunks saved: doc: linux-configure.canvas ,chunks: 14 (new:14, recycled:0, cached:0)
2024/6/2 12:32:47->STORAGE -> DB (plain) python.md
2024/6/2 12:32:47->STORAGE -> DB (newnote) tmp2.json
2024/6/2 12:32:47->STORAGE -> DB (plain) pages/Unsupervised Label Noise Modeling and Loss Correction.md
2024/6/2 12:32:47->STORAGE -> DB (plain) pages/Toward robustness against label noise in training deep discriminative neural networks.md
2024/6/2 12:32:47->STORAGE -> DB (plain) pages/Hybrid attention-based prototypical networks for noisy few-shot relation classification.md
2024/6/2 12:32:47->STORAGE -> DB (plain) Machine Configuration.canvas
2024/6/2 12:32:48->STORAGE -> DB (plain) linux-configure.canvas
2024/6/2 12:32:48->UPDATE DATABASE: DONE:10, FAILED:0, LAST:588
2024/6/2 12:32:49->Chunks saved: doc: livesync.md ,chunks: 10 (new:9, recycled:0, cached:1)
2024/6/2 12:32:49->STORAGE -> DB (plain) livesync.md
2024/6/2 12:32:58->Chunks saved: doc: latex_dict.pkl ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:32:58->Chunks saved: doc: Learning.canvas ,chunks: 80 (new:80, recycled:0, cached:0)
2024/6/2 12:32:59->STORAGE -> DB (newnote) latex_dict.pkl
2024/6/2 12:33:00->STORAGE -> DB (plain) Learning.canvas
2024/6/2 12:33:02->Chunks saved: doc: ITech/py/为什么 Python 对某些功能（例如 list.index()）使用方法来实现，而其他功能（例如 len(List)）使用函数实现？.md ,chunks: 2 (new:2, recycled:0, cached:0)
2024/6/2 12:33:03->STORAGE -> DB (plain) ITech/py/为什么 Python 对某些功能（例如 list.index()）使用方法来实现，而其他功能（例如 len(List)）使用函数实现？.md
2024/6/2 12:33:04->Chunks saved: doc: Github Action 自动推送代码到 hugginface.md ,chunks: 9 (new:9, recycled:0, cached:0)
2024/6/2 12:33:06->Chunks saved: doc: cloudflare R2 云存储.md ,chunks: 17 (new:17, recycled:0, cached:0)
2024/6/2 12:33:07->Chunks saved: doc: dida/第一.md ,chunks: 18 (new:18, recycled:0, cached:0)
2024/6/2 12:33:08->STORAGE -> DB (plain) Github Action 自动推送代码到 hugginface.md
2024/6/2 12:33:14->Chunks saved: doc: dida/科研.md ,chunks: 20 (new:19, recycled:0, cached:1)
2024/6/2 12:33:14->STORAGE -> DB (plain) cloudflare R2 云存储.md
2024/6/2 12:33:14->STORAGE -> DB (plain) dida/第一.md
2024/6/2 12:33:14->Chunks saved: doc: dida/可解释.md ,chunks: 26 (new:24, recycled:0, cached:2)
2024/6/2 12:33:14->Chunks saved: doc: dida/研究助手.md ,chunks: 37 (new:35, recycled:0, cached:2)
2024/6/2 12:33:14->STORAGE -> DB (plain) dida/科研.md
2024/6/2 12:33:14->STORAGE -> DB (plain) dida/可解释.md
2024/6/2 12:33:15->Chunks saved: doc: dida/LightLearning.md ,chunks: 28 (new:26, recycled:0, cached:2)
2024/6/2 12:33:15->STORAGE -> DB (plain) dida/研究助手.md
2024/6/2 12:33:15->UPDATE DATABASE: DONE:20, FAILED:0, LAST:578
2024/6/2 12:33:15->STORAGE -> DB (plain) dida/LightLearning.md
2024/6/2 12:33:16->Chunks saved: doc: dida/用于生成.md ,chunks: 52 (new:50, recycled:0, cached:2)
2024/6/2 12:33:16->STORAGE -> DB (plain) dida/用于生成.md
2024/6/2 12:33:17->Chunks saved: doc: dida/Inbox.md ,chunks: 178 (new:177, recycled:1, cached:0)
2024/6/2 12:33:17->Setting markdown has been detected, but not changed.
2024/6/2 12:33:17->Chunks saved: doc: dida/HardLearning.md ,chunks: 24 (new:22, recycled:0, cached:2)
2024/6/2 12:33:17->Chunks saved: doc: Excalidraw/Drawing 2024-01-03 15.07.43.excalidraw.md ,chunks: 20 (new:20, recycled:0, cached:0)
2024/6/2 12:33:17->Chunks saved: doc: Accumulating.md ,chunks: 26 (new:25, recycled:0, cached:1)
2024/6/2 12:33:18->Chunks saved: doc: AC-Drive.canvas ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:33:18->Chunks saved: doc: 2-Output/Project/P-语言/T.md ,chunks: 5 (new:5, recycled:0, cached:0)
2024/6/2 12:33:18->Chunks saved: doc: 2-Output/Project/P-语言/T-English.md ,chunks: 10 (new:10, recycled:0, cached:0)
2024/6/2 12:33:18->STORAGE -> DB (plain) dida/Inbox.md
2024/6/2 12:33:18->Chunks saved: doc: 2-Output/Project/P-行为追踪/T-行为追踪.md ,chunks: 5 (new:5, recycled:0, cached:0)
2024/6/2 12:33:19->STORAGE -> DB (plain) Excalidraw/Drawing 2023-12-23 15.21.45.excalidraw.md
2024/6/2 12:33:19->STORAGE -> DB (plain) dida/HardLearning.md
2024/6/2 12:33:20->STORAGE -> DB (plain) Excalidraw/Drawing 2024-01-03 15.07.43.excalidraw.md
2024/6/2 12:33:20->Chunks saved: doc: 2-Output/Project/P-花钱/T-花钱.md ,chunks: 6 (new:6, recycled:0, cached:0)
2024/6/2 12:33:20->STORAGE -> DB (plain) Accumulating.md
2024/6/2 12:33:20->STORAGE -> DB (plain) AC-Drive.canvas
2024/6/2 12:33:20->STORAGE -> DB (plain) 2-Output/Project/P-语言/T.md
2024/6/2 12:33:20->STORAGE -> DB (plain) 2-Output/Project/P-语言/T-English.md
2024/6/2 12:33:20->UPDATE DATABASE: DONE:30, FAILED:0, LAST:568
2024/6/2 12:33:21->STORAGE -> DB (plain) 2-Output/Project/P-行为追踪/T-行为追踪.md
2024/6/2 12:33:21->Chunks saved: doc: 2-Output/Project/P-搞钱/T-软视频.md ,chunks: 6 (new:6, recycled:0, cached:0)
2024/6/2 12:33:21->Chunks saved: doc: 2-Output/Project/P-搞钱/T-知识库.md ,chunks: 7 (new:7, recycled:0, cached:0)
2024/6/2 12:33:21->STORAGE -> DB (plain) 2-Output/Project/P-花钱/T-花钱.md
2024/6/2 12:33:21->Chunks saved: doc: 2-Output/Project/P-微习惯/T-Default.md ,chunks: 3 (new:3, recycled:0, cached:0)
2024/6/2 12:33:21->Chunks saved: doc: 2-Output/Project/P-微小项目组/熊苑教育.md ,chunks: 333 (new:329, recycled:0, cached:4)
2024/6/2 12:33:21->Chunks saved: doc: 2-Output/Project/P-微小项目组/毕业/T-毕业.md ,chunks: 7 (new:7, recycled:0, cached:0)
2024/6/2 12:33:22->Chunks saved: doc: 2-Output/Project/P-微小项目组/机器时代的艺术流变/机器时代的艺术流变-艺术与技术流变分析框架.md ,chunks: 54 (new:53, recycled:0, cached:1)
2024/6/2 12:33:22->Chunks saved: doc: 2-Output/Project/P-微小项目组/机器时代的艺术流变/机器时代的艺术流变-相关研究.md ,chunks: 63 (new:63, recycled:0, cached:0)
2024/6/2 12:33:22->STORAGE -> DB (plain) 2-Output/Project/P-搞钱/T-软视频.md
2024/6/2 12:33:22->Chunks saved: doc: 2-Output/Project/P-微小项目组/ContraFace.md ,chunks: 82 (new:82, recycled:0, cached:0)
2024/6/2 12:33:22->STORAGE -> DB (plain) 2-Output/Project/P-搞钱/T-知识库.md
2024/6/2 12:33:22->Chunks saved: doc: 2-Output/Project/P-基础云服务/T-云行走.md ,chunks: 6 (new:6, recycled:0, cached:0)
2024/6/2 12:33:23->STORAGE -> DB (plain) 2-Output/Project/P-微习惯/T-Default.md
2024/6/2 12:33:23->STORAGE -> DB (plain) 2-Output/Project/P-微小项目组/熊苑教育.md
2024/6/2 12:33:23->STORAGE -> DB (plain) 2-Output/Project/P-微小项目组/毕业/T-毕业.md
2024/6/2 12:33:23->STORAGE -> DB (plain) 2-Output/Project/P-微小项目组/机器时代的艺术流变/机器时代的艺术流变-艺术与技术流变分析框架.md
2024/6/2 12:33:23->STORAGE -> DB (plain) 2-Output/Project/P-微小项目组/机器时代的艺术流变/机器时代的艺术流变-相关研究.md
2024/6/2 12:33:23->Chunks saved: doc: 2-Output/Project/P-基础云服务/T-博客.md ,chunks: 6 (new:6, recycled:0, cached:0)
2024/6/2 12:33:24->STORAGE -> DB (plain) 2-Output/Project/P-微小项目组/ContraFace.md
2024/6/2 12:33:24->UPDATE DATABASE: DONE:40, FAILED:0, LAST:558
2024/6/2 12:33:24->Chunks saved: doc: 2-Output/Project/P-基础云服务/T-云可达.md ,chunks: 24 (new:23, recycled:0, cached:1)
2024/6/2 12:33:24->STORAGE -> DB (plain) 2-Output/Project/P-基础云服务/T-云行走.md
2024/6/2 12:33:24->Chunks saved: doc: 2-Output/Project/P-OB/T-重构.md ,chunks: 13 (new:13, recycled:0, cached:0)
2024/6/2 12:33:24->STORAGE -> DB (plain) 2-Output/Project/P-基础云服务/T-博客.md
2024/6/2 12:33:24->Chunks saved: doc: 2-Output/Project/P-OB/T-扩展用法.md ,chunks: 19 (new:18, recycled:1, cached:0)
2024/6/2 12:33:24->Chunks saved: doc: 2-Output/Project/P-OB/T-Ex.md ,chunks: 33 (new:31, recycled:1, cached:1)
2024/6/2 12:33:25->Chunks saved: doc: 2-Output/Project/P-OB/demo.md ,chunks: 4 (new:4, recycled:0, cached:0)
2024/6/2 12:33:25->STORAGE -> DB (plain) 2-Output/Project/P-基础云服务/T-云可达.md
2024/6/2 12:33:25->Chunks saved: doc: 2-Output/Project/P-Windows优化/T-WM.md ,chunks: 8 (new:8, recycled:0, cached:0)
2024/6/2 12:33:25->Chunks saved: doc: 2-Output/Project/P-IT通识/T.md ,chunks: 7 (new:6, recycled:0, cached:1)
2024/6/2 12:33:25->STORAGE -> DB (plain) 2-Output/Project/P-OB/T-重构.md
2024/6/2 12:33:25->Chunks saved: doc: 2-Output/Project/English.md ,chunks: 11 (new:11, recycled:0, cached:0)
2024/6/2 12:33:26->STORAGE -> DB (plain) 2-Output/Project/P-OB/T-扩展用法.md
2024/6/2 12:33:26->STORAGE -> DB (plain) 2-Output/Project/P-OB/T-Ex.md
2024/6/2 12:33:26->STORAGE -> DB (plain) 2-Output/Project/P-OB/demo.md
2024/6/2 12:33:26->Chunks saved: doc: 2-Output/玩意/奇葩科学.md ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:33:26->Chunks saved: doc: 2-Output/玩意/文思/article-领导者.md ,chunks: 2 (new:2, recycled:0, cached:0)
2024/6/2 12:33:26->STORAGE -> DB (plain) 2-Output/Project/P-Windows优化/T-WM.md
2024/6/2 12:33:26->STORAGE -> DB (plain) 2-Output/Project/P-IT通识/T.md
2024/6/2 12:33:27->Chunks saved: doc: 2-Output/玩意/文思/article-选校建议.md ,chunks: 28 (new:28, recycled:0, cached:0)
2024/6/2 12:33:27->STORAGE -> DB (plain) 2-Output/Project/English.md
2024/6/2 12:33:27->UPDATE DATABASE: DONE:50, FAILED:0, LAST:548
2024/6/2 12:33:27->STORAGE -> DB (plain) 2-Output/玩意/奇葩科学.md
2024/6/2 12:33:27->STORAGE -> DB (plain) 2-Output/玩意/文思/article-领导者.md
2024/6/2 12:33:27->Chunks saved: doc: 2-Output/玩意/文思/article-渴信症.md ,chunks: 11 (new:11, recycled:0, cached:0)
2024/6/2 12:33:27->Chunks saved: doc: 2-Output/玩意/文思/article-进取心.md ,chunks: 5 (new:5, recycled:0, cached:0)
2024/6/2 12:33:27->Chunks saved: doc: 2-Output/玩意/文思/article-机器时代的艺术流变.md ,chunks: 12 (new:12, recycled:0, cached:0)
2024/6/2 12:33:28->Chunks saved: doc: 2-Output/玩意/文思/article-未你给我的信.md ,chunks: 19 (new:19, recycled:0, cached:0)
2024/6/2 12:33:28->STORAGE -> DB (plain) 2-Output/玩意/文思/article-选校建议.md
2024/6/2 12:33:28->Chunks saved: doc: 2-Output/玩意/文思/article-散碎流矢.md ,chunks: 5 (new:5, recycled:0, cached:0)
2024/6/2 12:33:28->Chunks saved: doc: 2-Output/玩意/文思/article-我的存在.md ,chunks: 8 (new:8, recycled:0, cached:0)
2024/6/2 12:33:28->STORAGE -> DB (plain) 2-Output/玩意/文思/article-渴信症.md
2024/6/2 12:33:28->STORAGE -> DB (plain) 2-Output/玩意/文思/article-进取心.md
2024/6/2 12:33:28->STORAGE -> DB (plain) 2-Output/玩意/文思/article-机器时代的艺术流变.md
2024/6/2 12:33:29->STORAGE -> DB (plain) 2-Output/玩意/文思/article-未你给我的信.md
2024/6/2 12:33:29->Chunks saved: doc: 2-Output/玩意/文思/article-坚恪.md ,chunks: 10 (new:10, recycled:0, cached:0)
2024/6/2 12:33:29->Chunks saved: doc: 2-Output/玩意/文思/article-一般的腿玩年.md ,chunks: 8 (new:8, recycled:0, cached:0)
2024/6/2 12:33:29->Chunks saved: doc: 2-Output/玩意/文思/article-20年.md ,chunks: 20 (new:20, recycled:0, cached:0)
2024/6/2 12:33:29->STORAGE -> DB (plain) 2-Output/玩意/文思/article-散碎流矢.md
2024/6/2 12:33:29->STORAGE -> DB (plain) 2-Output/玩意/文思/article-我的存在.md
2024/6/2 12:33:29->Chunks saved: doc: 2-Output/玩意/ta言.md ,chunks: 19 (new:19, recycled:0, cached:0)
2024/6/2 12:33:30->STORAGE -> DB (plain) 2-Output/玩意/文思/article-坚恪.md
2024/6/2 12:33:30->UPDATE DATABASE: DONE:60, FAILED:0, LAST:538
2024/6/2 12:33:30->STORAGE -> DB (plain) 2-Output/玩意/文思/article-一般的腿玩年.md
2024/6/2 12:33:30->STORAGE -> DB (plain) 2-Output/玩意/文思/article-20年.md
2024/6/2 12:33:30->Chunks saved: doc: 2-Output/Journal/words-2024.md ,chunks: 8 (new:8, recycled:0, cached:0)
2024/6/2 12:33:30->Chunks saved: doc: 2-Output/Journal/words-2023.md ,chunks: 38 (new:38, recycled:0, cached:0)
2024/6/2 12:33:31->Chunks saved: doc: 2-Output/Journal/words-2021.md ,chunks: 59 (new:59, recycled:0, cached:0)
2024/6/2 12:33:31->Chunks saved: doc: 2-Output/Journal/words-2022.md ,chunks: 18 (new:18, recycled:0, cached:0)
2024/6/2 12:33:31->STORAGE -> DB (plain) 2-Output/玩意/ta言.md
2024/6/2 12:33:31->STORAGE -> DB (plain) 2-Output/Journal/words-2024.md
2024/6/2 12:33:31->STORAGE -> DB (plain) 2-Output/Journal/words-2023.md
2024/6/2 12:33:32->STORAGE -> DB (plain) 2-Output/Journal/words-2021.md
2024/6/2 12:33:32->STORAGE -> DB (plain) 2-Output/Journal/words-2022.md
2024/6/2 12:33:32->Chunks saved: doc: 2-Output/Journal/words-2020.md ,chunks: 238 (new:237, recycled:0, cached:1)
2024/6/2 12:33:32->Chunks saved: doc: 2-Output/Journal/words-2019.md ,chunks: 34 (new:34, recycled:0, cached:0)
2024/6/2 12:33:32->Chunks saved: doc: 2-Output/Journal/2024-05-21.md ,chunks: 11 (new:10, recycled:1, cached:0)
2024/6/2 12:33:33->Chunks saved: doc: 2-Output/Journal/2024-05-18.md ,chunks: 13 (new:4, recycled:0, cached:9)
2024/6/2 12:33:33->Chunks saved: doc: 2-Output/Journal/2024-05-19.md ,chunks: 10 (new:3, recycled:0, cached:7)
2024/6/2 12:33:33->STORAGE -> DB (plain) 2-Output/Journal/words-2020.md
2024/6/2 12:33:33->STORAGE -> DB (plain) 2-Output/Journal/words-2019.md
2024/6/2 12:33:33->STORAGE -> DB (plain) 2-Output/Journal/2024-05-21.md
2024/6/2 12:33:33->UPDATE DATABASE: DONE:70, FAILED:0, LAST:528
2024/6/2 12:33:33->STORAGE -> DB (plain) 2-Output/Journal/2024-05-18.md
2024/6/2 12:33:33->STORAGE -> DB (plain) 2-Output/Journal/2024-05-19.md
2024/6/2 12:33:33->Chunks saved: doc: 2-Output/Journal/2024-05-16.md ,chunks: 19 (new:10, recycled:0, cached:9)
2024/6/2 12:33:33->Chunks saved: doc: 2-Output/Journal/2024-05-17.md ,chunks: 13 (new:4, recycled:0, cached:9)
2024/6/2 12:33:33->Chunks saved: doc: 2-Output/Journal/2024-05-14.md ,chunks: 18 (new:11, recycled:0, cached:7)
2024/6/2 12:33:34->Chunks saved: doc: 2-Output/Journal/2024-05-15.md ,chunks: 11 (new:2, recycled:0, cached:9)
2024/6/2 12:33:34->Chunks saved: doc: 2-Output/Journal/2024-05-13.md ,chunks: 14 (new:5, recycled:0, cached:9)
2024/6/2 12:33:34->STORAGE -> DB (plain) 2-Output/Journal/2024-05-16.md
2024/6/2 12:33:34->STORAGE -> DB (plain) 2-Output/Journal/2024-05-17.md
2024/6/2 12:33:34->STORAGE -> DB (plain) 2-Output/Journal/2024-05-14.md
2024/6/2 12:33:34->STORAGE -> DB (plain) 2-Output/Journal/2024-05-15.md
2024/6/2 12:33:34->STORAGE -> DB (plain) 2-Output/Journal/2024-05-13.md
2024/6/2 12:33:34->Chunks saved: doc: 2-Output/Journal/2024-05-12.md ,chunks: 20 (new:12, recycled:0, cached:8)
2024/6/2 12:33:34->Chunks saved: doc: 2-Output/Journal/2024-05-10.md ,ch
===================================
===================================

2024/6/2 12:34:26->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-tool.md
2024/6/2 12:34:26->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-内核.md
2024/6/2 12:34:26->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-system.md ,chunks: 5 (new:4, recycled:0, cached:1)
2024/6/2 12:34:26->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-storage.md ,chunks: 7 (new:6, recycled:0, cached:1)
2024/6/2 12:34:26->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-system.md
2024/6/2 12:34:26->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-storage.md
2024/6/2 12:34:26->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-snap.md ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-storage-lvm-ubuntu.md ,chunks: 13 (new:12, recycled:0, cached:1)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-setting-ubuntu.md ,chunks: 2 (new:2, recycled:0, cached:0)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-problem.md ,chunks: 14 (new:14, recycled:0, cached:0)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-network.md ,chunks: 4 (new:3, recycled:0, cached:1)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-network-登录认证无线网络.md ,chunks: 46 (new:33, recycled:0, cached:13)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-network-dns.md ,chunks: 8 (new:8, recycled:0, cached:0)
2024/6/2 12:34:27->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-manage.md ,chunks: 11 (new:11, recycled:0, cached:0)
2024/6/2 12:34:27->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-snap.md
2024/6/2 12:34:27->UPDATE DATABASE: DONE:240, FAILED:0, LAST:358
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-storage-lvm-ubuntu.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-setting-ubuntu.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-problem.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-network.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-network-登录认证无线网络.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-network-dns.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-manage.md
2024/6/2 12:34:28->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-manjaro-setting.md ,chunks: 55 (new:54, recycled:0, cached:1)
2024/6/2 12:34:28->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-install.md ,chunks: 29 (new:24, recycled:1, cached:4)
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-manjaro-setting.md
2024/6/2 12:34:28->STORAGE -> DB (plain) 1-Earnings/大工具系统/OS/linux/linux-install.md
2024/6/2 12:34:28->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-GPU.md ,chunks: 8 (new:7, recycled:0, cached:1)
2024/6/2 12:34:28->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/linux-aur-加速脚本.md ,chunks: 1 (new:1, recycled:0, cached:0)
2024/6/2 12:34:28->Chunks saved: doc: 1-Earnings/大工具系统/OS/linux/KDE.md ,chunks: 19 (new:19, recycled:0, cached:0)
2024/6/2 12:34:28->Chunks saved: doc: 1-Earnings/大工具系统/OS/Android in PC.md ,chunks: 16 (new:15, recycled:0, cached:1)
2024/6/2 12:34:29->Chunks saved: doc: 1-Earnings/古文/千字文.md ,chunks: 63 (new:63, recycled:0, cached:0)
2024/6/2 12:34:29->Chunks saved: doc: 1-Earnings/历史/疫情时代.md ,chunks: 8 (new:8, recycled:0, cached:0)
```

### configs

```
---- Obsidian info ----
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.12 Chrome/120.0.6099.283 Electron/28.2.3 Safari/537.36
---- remote config ----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.23.12
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: true
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: thinkbook16
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 1d10bb0fbc469dde
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 5
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 40
minimumIntervalOfReadChunksOnline: 50
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: livesync.md
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 0
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: zh
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: true
processSmallFilesInUIThread: false
configPassphrase: ""
preset: ""
syncMode: ONEVENTS
dummy: 0
```
