### ISSUE TITLE
[ModuleConflictResolver]  conflict:Nothing to do

### ISSUE THREAD

**Issue by 0zd0** [vrtmrz/obsidian-livesync#542]
## Abstract
After installing 0.24 can't get note changes

## Expected behaviour
- I go to the note
- The plugin receives changes

## Actually happened
- 17.11.2024, 19:14:23->[ModuleConflictResolver]  conflict:Nothing to do:note.md

## Reproducing procedure

1. Installed the plugin on a clean device and synchronized the database, all notes were loaded
2. I re-entered the application, opened the note and in the log it shows ModuleConflictResolver

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.7.6 Chrome/128.0.6613.186 Electron/32.2.3 Safari/537.36
FileSystem: insensitive
---- remote config ----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.1
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: true
resolveConflictsByNewerFile: true
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: windows
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: true
autoSweepPlugins: true
autoSweepPluginsPeriodic: true
notifyPluginOrSettingUpdated: true
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: a2436299e890fcb2
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 2000
usePluginSyncV2: false
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: true
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0
```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```

```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
17.11.2024, 19:17:46->[ModuleObsidianMenu]: Injected (Every) $everyOnloadStart 
17.11.2024, 19:17:46->[ModuleObsidianDocumentHistory]: Injected (Every) $everyOnloadStart 
17.11.2024, 19:17:46->[ModuleInteractiveConflictResolver]: Injected (Every) $everyOnloadStart 
17.11.2024, 19:17:46->[ModuleObsidianGlobalHistory]: Injected (Every) $everyOnloadStart 
17.11.2024, 19:17:46->[ModuleDev]: Injected (Every) $everyOnloadStart 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected (Every) $everyOnloadAfterLoadSettings 
17.11.2024, 19:17:46->[ModuleKeyValueDB]: Injected (Every) $everyOnloadAfterLoadSettings 
17.11.2024, 19:17:46->[ModuleLog]: Injected (Every) $everyOnloadAfterLoadSettings 
17.11.2024, 19:17:46->[ModuleDev]: Injected (Every) $everyOnloadAfterLoadSettings 
17.11.2024, 19:17:46->[ModuleReplicateTest]: Injected (Every) $everyOnloadAfterLoadSettings 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Every) $everyOnloadAfterLoadSettings 
17.11.2024, 19:17:46->[ModuleDatabaseFileAccess]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleTargetFilter]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleFileAccessObsidian]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleLog]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleInputUIObsidian]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleObsidianMenu]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleRebuilder]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleSetupObsidian]: Injected (Every) $everyOnload 
17.11.2024, 19:17:46->[ModuleFileHandler]: Injected (Any) $anyHandlerProcessesFileEvent 
17.11.2024, 19:17:46->[ModuleLog]: Injected (All) $allStartOnUnload 
17.11.2024, 19:17:46->[ModulePeriodicProcess]: Injected (All) $allOnUnload 
17.11.2024, 19:17:46->[ModuleFileAccessObsidian]: Injected (All) $allOnUnload 
17.11.2024, 19:17:46->[ModuleLocalDatabaseObsidian]: Injected $$openDatabase 
17.11.2024, 19:17:46->[ModuleLiveSyncMain]: Injected $$realizeSettingSyncMode 
17.11.2024, 19:17:46->[ModuleObsidianEvents]: Injected $$performRestart 
17.11.2024, 19:17:46->[ModuleObsidianSettings]: Injected $$clearUsedPassphrase 
17.11.2024, 19:17:46->[ModuleObsidianSettings]: Injected $$loadSettings 
17.11.2024, 19:17:46->[ModuleObsidianSettings]: Injected $$saveDeviceAndVaultName 
17.11.2024, 19:17:46->[ModuleObsidianSettings]: Injected $$saveSettingData 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Any) $anyProcessOptionalFileEvent 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Any) $anyProcessOptionalFileEvent 
17.11.2024, 19:17:46->[ModuleFileAccessObsidian]: Injected (Every) $everyCommitPendingFileEvent 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Any) $anyGetOptionalConflictCheckMethod 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Any) $anyGetOptionalConflictCheckMethod 
17.11.2024, 19:17:46->[ModuleConflictChecker]: Injected $$queueConflictCheckIfOpen 
17.11.2024, 19:17:46->[ModuleConflictChecker]: Injected $$queueConflictCheck 
17.11.2024, 19:17:46->[ModuleConflictChecker]: Injected $$waitForAllConflictProcessed 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Any) $anyProcessOptionalSyncFiles 
17.11.2024, 19:17:46->[ModuleFileHandler]: Injected (Any) $anyProcessReplicatedDoc 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected $$parseReplicationResult 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Any) $anyModuleParsedReplicationResultItem 
17.11.2024, 19:17:46->[ModulePeriodicProcess]: Injected (Every) $everyBeforeRealizeSetting 
17.11.2024, 19:17:46->[ModulePeriodicProcess]: Injected (Every) $everyAfterRealizeSetting 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Every) $everyRealizeSettingSyncMode 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Every) $everyRealizeSettingSyncMode 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected (Every) $everyBeforeSuspendProcess 
17.11.2024, 19:17:46->[ModulePeriodicProcess]: Injected (Every) $everyBeforeSuspendProcess 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Every) $everyOnResumeProcess 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Every) $everyOnResumeProcess 
17.11.2024, 19:17:46->[ModuleReplicatorCouchDB]: Injected (Every) $everyAfterResumeProcess 
17.11.2024, 19:17:46->[ModulePeriodicProcess]: Injected (Every) $everyAfterResumeProcess 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Every) $everyAfterResumeProcess 
17.11.2024, 19:17:46->[ModuleResolvingMismatchedTweaks]: Injected $$askResolvingMismatchedTweaks 
17.11.2024, 19:17:46->[ModuleResolvingMismatchedTweaks]: Injected $$checkAndAskUseRemoteConfiguration 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected (Every) $everyBeforeReplicate 
17.11.2024, 19:17:46->[ModuleReplicateTest]: Injected (Every) $everyBeforeReplicate 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Every) $everyBeforeReplicate 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Every) $everyBeforeReplicate 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected $$replicate 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Every) $everyOnDatabaseInitialized 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Every) $everyOnDatabaseInitialized 
17.11.2024, 19:17:46->[ModuleInitializerFile]: Injected $$initializeDatabase 
17.11.2024, 19:17:46->[ModuleResolvingMismatchedTweaks]: Injected (Any) $anyAfterConnectCheckFailed 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected $$replicateAllToServer 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected $$replicateAllFromServer 
17.11.2024, 19:17:46->[ModuleRemoteGovernor]: Injected $$markRemoteLocked 
17.11.2024, 19:17:46->[ModuleRemoteGovernor]: Injected $$markRemoteUnlocked 
17.11.2024, 19:17:46->[ModuleRemoteGovernor]: Injected $$markRemoteResolved 
17.11.2024, 19:17:46->[ModuleTargetFilter]: Injected $$isFileSizeExceeded 
17.11.2024, 19:17:46->[ModuleInitializerFile]: Injected $$performFullScan 
17.11.2024, 19:17:46->[ModuleInteractiveConflictResolver]: Injected (Any) $anyResolveConflictByUI 
17.11.2024, 19:17:46->[ModuleConflictResolver]: Injected $$resolveConflictByDeletingRev 
17.11.2024, 19:17:46->[ModuleConflictResolver]: Injected $$resolveConflict 
17.11.2024, 19:17:46->[ModuleConflictResolver]: Injected (Any) $anyResolveConflictByNewest 
17.11.2024, 19:17:46->[ModuleReplicator]: Injected $$waitForReplicationOnce 
17.11.2024, 19:17:46->[ModuleRebuilder]: Injected $$resetLocalDatabase 
17.11.2024, 19:17:46->[ModuleRebuilder]: Injected $$tryResetRemoteDatabase 
17.11.2024, 19:17:46->[ModuleRebuilder]: Injected $$tryCreateRemoteDatabase 
17.11.2024, 19:17:46->[ModuleTargetFilter]: Injected $$isIgnoredByIgnoreFiles 
17.11.2024, 19:17:46->[ModuleTargetFilter]: Injected $$isTargetFile 
17.11.2024, 19:17:46->[ModuleObsidianEvents]: Injected $$askReload 
17.11.2024, 19:17:46->[ModuleObsidianEvents]: Injected $$scheduleAppReload 
17.11.2024, 19:17:46->[ModuleRebuilder]: Injected (All) $allSuspendAllSync 
17.11.2024, 19:17:46->[ConfigSync]: Injected (All) $allSuspendExtraSync 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (All) $allSuspendExtraSync 
17.11.2024, 19:17:46->[ConfigSync]: Injected (All) $allAskUsingOptionalSyncFeature 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (All) $allAskUsingOptionalSyncFeature 
17.11.2024, 19:17:46->[ConfigSync]: Injected (Any) $anyConfigureOptionalSyncFeature 
17.11.2024, 19:17:46->[HiddenFileSync]: Injected (Any) $anyConfigureOptionalSyncFeature 
17.11.2024, 19:17:46->[ModuleObsidianMenu]: Injected $$showView 
17.11.2024, 19:17:46->[ModuleDatabaseFileAccess]: Injected (Every) $everyModuleTest 
17.11.2024, 19:17:46->[ModuleDev]: Injected (Every) $everyModuleTest 
17.11.2024, 19:17:46->[ModuleReplicateTest]: Injected (Every) $everyModuleTestMultiDevice 
17.11.2024, 19:17:46->[ModuleIntegratedTest]: Injected (Every) $everyModuleTestMultiDevice 
17.11.2024, 19:17:46->[ModuleDev]: Injected $$addTestResult 
17.11.2024, 19:17:46->[ModuleObsidianAPI]: Injected (Any) $anyGetAppId 
17.11.2024, 19:17:46->Injected   modules for ObsidianLiveSyncPlugin
17.11.2024, 19:17:46->[ModuleLiveSyncMain]  loading plugin
17.11.2024, 19:17:46->[ModuleLiveSyncMain]  Self-hosted LiveSync v0.24.1 0.24.1
17.11.2024, 19:17:46->xxhash for plugin initialised
17.11.2024, 19:17:46->[HiddenFileSync]  Hidden file will skip 0 files
17.11.2024, 19:17:46->[ModuleLocalDatabaseObsidian]  Waiting for ready...
17.11.2024, 19:17:46->Cache initialized 10 / 1000000000
17.11.2024, 19:17:46->Cache initialized 300 / 50000000
17.11.2024, 19:17:46->Newer xxhash has been initialised
17.11.2024, 19:17:46->Opening Database...
17.11.2024, 19:17:46->Database info
17.11.2024, 19:17:46->{
  "doc_count": 1087,
  "update_seq": 1270,
  "db_name": "Obsidian Vault-a2436299e890fcb2-livesync-v2-indexeddb",
  "auto_compaction": false,
  "adapter": "indexeddb"
}
17.11.2024, 19:17:46->Database is now ready.
17.11.2024, 19:17:46->[ModuleObsidianEvents]  Modifying callback of the save command
17.11.2024, 19:17:46->[ModuleInitializerFile]  Opening the key-value database
17.11.2024, 19:17:46->[ModuleInitializerFile]  Initialize and checking database files
17.11.2024, 19:17:46->[ModuleInitializerFile]  Checking deleted files
17.11.2024, 19:17:46->[ModuleInitializerFile]  Collecting local files on the storage
17.11.2024, 19:17:46->[ModuleInitializerFile]  Collecting local files on the DB
17.11.2024, 19:17:46->[ModuleInitializerFile]  Collecting local files on the DB: 25
17.11.2024, 19:17:46->[ModuleInitializerFile]  Collecting local files on the DB: 50
17.11.2024, 19:17:46->[ModuleInitializerFile]  Total files in the database: 67
17.11.2024, 19:17:46->[ModuleInitializerFile]  Total files in the storage: 41
17.11.2024, 19:17:46->[ModuleInitializerFile]  Total files: 67
17.11.2024, 19:17:46->[ModuleInitializerFile]  Files exist only in storage: 0
17.11.2024, 19:17:46->[ModuleInitializerFile]  Files exist only in database: 26
17.11.2024, 19:17:46->[ModuleInitializerFile]  Files exist both in storage and database: 41
17.11.2024, 19:17:46->[ModuleInitializerFile]  Synchronising...
17.11.2024, 19:17:46->[ModuleInitializerFile]  UPDATE DATABASE: Nothing to do
17.11.2024, 19:17:46->[ModuleInitializerFile]  UPDATE STORAGE
17.11.2024, 19:17:46->[ModuleInitializerFile]  SYNC DATABASE AND STORAGE
17.11.2024, 19:17:46->[ModuleInitializerFile]  UPDATE STORAGE: DONE:10, FAILED:0, LAST:15
17.11.2024, 19:17:46->[ModuleInitializerFile]  Initialized, NOW TRACKING!
17.11.2024, 19:17:46->[ConfigSync]  Scanning customizations...
17.11.2024, 19:17:46->[ConfigSync]  Scanning customizing files.
17.11.2024, 19:17:46->[ModuleInitializerFile]  UPDATE STORAGE: DONE:10, FAILED:0, LAST:15
SYNC DATABASE AND STORAGE All done: DONE:41, FAILED:0
17.11.2024, 19:17:46->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/app.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:46->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/appearance.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:46->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/community-plugins.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:46->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/core-plugins.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:46->Chunks saved (with fixed): doc: windows/CONFIG/workspace.json.md ,chunks: 5 (new:3, recycled:0, cached:2)
17.11.2024, 19:17:46->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/workspace.json.md: (config) Done
17.11.2024, 19:17:46->[ConfigSync]  STORAGE --> DB:ix:windows/PLUGIN_DATA/obsidian-icon-folder.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  Scanning customizations : done
17.11.2024, 19:17:47->Cache initialized 300 / 50000000
17.11.2024, 19:17:47->[ConfigSync]  Scanning customizing files.
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/app.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/appearance.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/community-plugins.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/community-plugins.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/core-plugins.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/workspace.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/PLUGIN_DATA/obsidian-icon-folder.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ConfigSync]  STORAGE --> DB:ix:windows/CONFIG/workspace.json.md: (config) Skipped (Same content)
17.11.2024, 19:17:47->[ModuleLiveSyncMain]  Additional safety scan..
17.11.2024, 19:17:47->[ModuleInteractiveConflictResolver]  Checking conflicted files
17.11.2024, 19:17:47->Before LiveSync, start OneShot once...
17.11.2024, 19:17:47->OneShot Sync begin... (pullOnly)
17.11.2024, 19:17:48->[ModuleInteractiveConflictResolver]  There are no conflicted files
17.11.2024, 19:17:48->[ModuleCheckRemoteSize]  Checking storage sizes
17.11.2024, 19:17:48->[ModuleCheckRemoteSize]  Remote storage size: 36.68MB
17.11.2024, 19:17:48->[ModuleLiveSyncMain]  Additional safety scan done
17.11.2024, 19:17:49->Replication paused
17.11.2024, 19:17:49->Replication completed
17.11.2024, 19:17:49->LiveSync begin...
17.11.2024, 19:17:49->Replication activated
17.11.2024, 19:17:50->Replication paused
17.11.2024, 19:17:53->[ModuleConflictResolver]  conflict:Nothing to do:note.md
```
</details>

### Other information, insights and intuition.
On another device I updated from version 0.23.XX to 0.24 and now there is the same error
