### ISSUE TITLE
Decryption error on obsidian (docker)

### ISSUE THREAD

**Issue by anpalcactus** [vrtmrz/obsidian-livesync#551]
## Abstract
I'm running self-hosted CouchDB and three client instances (iphone, pc, docker container on vds (https://github.com/linuxserver/docker-obsidian) ). After setting up livesync **it works perfectly fine on iphone and pc**, though the docker instance shows errors when trying to replicate/sync. |

I ensured that the codephrase used for encoding and decoding is the same. 
Configuration of the db is checked fine. 
No experimental dynamic iteration. 
Path obfuscation on. 
Same (0.24.2) plugin version on every platform. 
The same access to the database over https persistent cloudflare tunnel linked to my own subdomain. 
Tried both fast URI and minimal setup, no luck. 
Tried clean obsidian install. Tried starting from a new db. 

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Everything synchronised

## Actually happened
- Synchronisation has been cancelled with the message `Decryption failed (23)` `TypeError:Cannot read properties of undefined (reading 'processing')` (captured in the attached log)
- No files synchronised

## Reproducing procedure

1. Configure LiveSync as in the attached material.
2. Obsidian container has a new empty vault, only livesync plugin installed.
3. Paste URI  OR Minimal setup OR manual setup leads to an error. 
4. Trying to replicate/sync afterwards leads to the same error.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.7.7 Chrome/128.0.6613.186 Electron/32.2.5 Safari/537.36
FileSystem: sensitive
---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  methods: GET, PUT, POST, HEAD, DELETE
  origins: "*"
chttpd:
  bind_address: 127.0.0.1
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: d9ec0f24086ced2bac345c95884ea657
log:
  file: /var/log/couchdb/couchdb.log
  writer: file
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.2
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: vds
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 157db69a6916ea3e
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: true
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 0
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: true
useAdvancedMode: true
usePowerUserMode: true
useEdgeCaseMode: true
enableDebugTools: false
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
<!-- paste here -->
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Replication activated
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Decryption failed.
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->TypeError:Cannot read properties of undefined (reading 'processing')
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->id:f:0234c4a7975c92c14c1b0863764d7b18ab763332a2d968be3f5ff11beb43a428-1-4e6739c4
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Decryption failed.
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->TypeError:Cannot read properties of undefined (reading 'processing')
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->id:f:0359cc4382b5c29ec873b0578fafeefefbd7b90db4b103f7a7d5da5a514cb6fa-1-6545d6a4
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Decryption failed.
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->TypeError:Cannot read properties of undefined (reading 'processing')
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->id:f:047b6c435d18537480f9ae579a7d802c937b3b293ba5c167dd51926f9752f7ca-1-fe1a37c3
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Decryption failed.
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->TypeError:Cannot read properties of undefined (reading 'processing')

<..>

Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->id:f:0bc97fe1ab6ded0b72dcbb42cbcd46d2a6a57dadb6aa1932be5d981ceaf35a45-1-79ab129c
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Decryption failed.
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->TypeError:Cannot read properties of undefined (reading 'processing')
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->id:f:0fe1c6b00da8a549aedfcea1e897b1261d1163da95211254620c1d8d179f1e16-1-573f4462
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Replication error
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Error:Cannot read properties of undefined (reading 'processing')
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Replication stopped.
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Replication error
Obsidian Vault-157db69a6916ea3e:12/3/2024, 8:59:36 PM->Error:Cannot read properties of undefined (reading 'processing')

```
</details>

### Other information, insights and intuition.

I'm using this docker image:
https://github.com/linuxserver/docker-obsidian
