### ISSUE TITLE
Multiple attempts to resolve a batch of conflicts in hidden files fail to resolve them.

### ISSUE THREAD

**Issue by izosozi** [vrtmrz/obsidian-livesync#554]
## Abstract

Multiple attempts to resolve a batch of conflicts in hidden files fail to resolve them, including fetching from the remote DB.

## Reproducing procedure

1. Enabled Hidden File Sync on both devices A and B
1. Made a change to a hidden file on device A
1. Waited for conflict to appear on device B
1. Pressed LiveSync Settings > Hatch > Resolve All (Resolve all conflicts with the newer version)

**Expected:**

The conflicts should be resolved in the background. No conflicts should appear in the "Pick a file to resolve conflict" menu

**Actual:**

The same conflicts as before appear in the conflict picker.

5. Enabled LiveSync Settings > Patches > Compatibility (Conflict Behaviour) > Apply Latest Change if Conflicting
1. Reloaded Obsidian

**Expected:**

The conflicts should be resolved in the background. No conflicts should appear in the "Pick a file to resolve conflict" menu

**Actual:**

The same conflicts as before appear in the conflict picker.

7. Disabled LiveSync Settings > Patches > Compatibility (Conflict Behaviour) > Resolve All
1. Reloaded Obsidian
1. Enabled LiveSync Settings > Sync Settings > Conflict resolution > (BETA) Always overwrite with a newer file
1. Reloaded Obsidian

**Expected:**

The conflicts should be resolved in the background. No conflicts should appear in the "Pick a file to resolve conflict" menu

**Actual:**

The same conflicts as before appear in the conflict picker.

11. Pressed LiveSync Settings > Maintenance > Rebuilding Operations (Local) > Fetch from remote w/o restarting
1. Selected "Fetch" when prompted about hidden files
1. Waited for process to complete and reloaded Obsidian

**Expected:**

There should be no conflicts since the local version is freshly fetched from the remote db. No conflicts should appear in the "Pick a file to resolve conflict" menu

**Actual:**

The same conflicts as before appear in the conflict picker.

14. Disabled LiveSync Settings > Sync Settings > Conflict resolution > (BETA) Always overwrite with a newer file
1. Enabled LiveSync Settings > Patches > Compatibility (Conflict Behaviour) > Apply Latest Change if Conflicting
1. Ran command "Resolve all conflicted files" in Command Palette

**Expected:**

All conflicts should be resolved in the background

**Actual:**

The same conflicts as before appear in the conflict picker., but they do get resolved automatically when clicked on one by one

### Report from the LiveSync
<details>
<summary>Report from hatch</summary>

```yaml
# ---- Obsidian info ----
# Navigator: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.7.7 Chrome/128.0.6613.186 Electron/32.2.5 Safari/537.36
# FileSystem: insensitive
# ---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: 6449e3015df52bb23673b5763bbbc71c
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

# ---- Plug-in config ---
version:0.24.3
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTP)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 10
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 3
batchSaveMaximumDelay: 30
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: false
showStatusOnStatusbar: false
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: node_modules\/, \.git, plugins\/obsidian-livesync\/, \.stversions, \.stfolder, \.trash, plugins\/remember-cursor-position\/cursor-positions\.json$, \.DS_Store, plugins\/obsidian-raindrop-highlights\/data\.json$, hotkeys\.json, workspace\.json, workspace-mobile\.json, plugins\/smart-connections\/data\.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: f207f9baa45a8afc
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: \.DS_Store|[]|^raindrop\/
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 1
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: true
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 40
minimumIntervalOfReadChunksOnline: 50
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: livesync-config.md
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 5000
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: true
usePowerUserMode: true
useEdgeCaseMode: true
enableDebugTools: false
configPassphrase: ""
preset: ""
syncMode: ONEVENTS
dummy: 0
```

</details>

### Plug-in log

<details>
<summary>Plug-in log</summary>

[output.txt](https://github.com/user-attachments/files/18084752/output.txt)

</details>

### Screenshots

Hidden files which failed to be resolved:

![image](https://github.com/user-attachments/assets/bffde154-f0e1-4721-9355-fd8df0846781)

### Other information, insights and intuition.

This issue may be a result of my own inaccurate expectations of what these settings do. If so, some more relabeling/description/documentation would be appreciated.

It is also possible that these conflicts were themselves being synchronized into the remote DB, which would explain why there were still conflicts after fetching.

Thank you for all that you do!
