### ISSUE TITLE
can't resolve config files with conflicts.

### ISSUE THREAD

**Issue by vinidlidoo** [vrtmrz/obsidian-livesync#563]
## Abstract
I can't resolve config files with conflicts.

## Expected behaviour
- Config files with conflicts are resolved.

## Actually happened
- Upon launching the app, I get a notification saying that Some files have been left conflicted! (see screenshot) 
- When I click on HERE, select a file with conflict, and hit enter, nothing happens.

## Reproducing procedure

1. see above. It happens systematically every time I launch the app. 

Note: If you do not catch the reproducing procedure, please let me know the frequency and signs.

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36
FileSystem: insensitive
---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: f8bab6acbe196108254ab665bede7c48
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.6
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: minimac
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: false
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: true
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 50
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 51d0d237ff2a5564
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 100
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 2000
usePluginSyncV2: false
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: false
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
<!-- paste here -->
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
2/30/2024, 9:42:04 AM->[ModuleInitializerFile]  Initialized, NOW TRACKING!
12/30/2024, 9:42:04 AM->[ConfigSync]  Scanning customizations...
12/30/2024, 9:42:04 AM->[ConfigSync]  Scanning customizing files.
12/30/2024, 9:42:05 AM->[ModuleInitializerFile]  UPDATE STORAGE All done: DONE:490, FAILED:0
12/30/2024, 9:42:05 AM->[ConfigSync]  STORAGE --> DB:ix:minimac/CONFIG/app.json.md: (config) Skipped (Same content)
12/30/2024, 9:42:05 AM->[ConfigSync]  STORAGE --> DB:ix:minimac/CONFIG/appearance.json.md: (config) Skipped (Same content)
12/30/2024, 9:42:05 AM->[ConfigSync]  STORAGE --> DB:ix:minimac/CONFIG/community-plugins.json.md: (config) Skipped (Same content)
12/30/2024, 9:42:05 AM->[ConfigSync]  STORAGE --> DB:ix:minimac/CONFIG/core-plugins.json.md: (config) Skipped (Same content)
12/30/2024, 9:42:05 AM->[ConfigSync]  STORAGE --> DB:ix:minimac/CONFIG/workspace.json.md: (config) Skipped (Same content)
12/30/2024, 9:42:05 AM->Chunks saved (with fixed): doc: minimac/PLUGIN_DATA/obsidian-livesync.md ,chunks: 5 (new:3, recycled:0, cached:2)
12/30/2024, 9:42:05 AM->[ConfigSync]  STORAGE --> DB:ix:minimac/PLUGIN_DATA/obsidian-livesync.md: (config) Done
12/30/2024, 9:42:05 AM->[ConfigSync]  Scanning customizations : done
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Track changes.
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Enumerating local files...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Enumerating database files...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Applying untracked changes...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Tracking statics:
Local files: 11
Database files: 11
Untracked local files: 0
Untracked database files: 0
Common untracked files: 0
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
Scanning storage files...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Known/Exist 11/11, Totally 11 files.
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
[Storage hidden file statics]
Known files: 11
Actual files: 11
All files: 11
Offline Changed files: 5
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Modification detected:.obsidian/app.json
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Modification detected:.obsidian/appearance.json
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Modification detected:.obsidian/community-plugins.json
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Modification detected:.obsidian/core-plugins.json
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Modification detected:.obsidian/workspace.json
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Nothing changed: .obsidian/app.json Nothing changed
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Storage -> DB ]
1/5
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Nothing changed: .obsidian/appearance.json Nothing changed
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Nothing changed: .obsidian/core-plugins.json Nothing changed
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Nothing changed: .obsidian/community-plugins.json Nothing changed
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Nothing changed: .obsidian/workspace.json Nothing changed
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Storage -> DB ]
Done  
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
Done  
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [Database hidden file statics]
All files: 11
Offline Changed files: 0
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ DB -> Storage ]
Done  
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Done  
12/30/2024, 9:42:05 AM->Cache initialized 300 / 50000000
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Track changes.
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Enumerating local files...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Enumerating database files...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Applying untracked changes...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Tracking statics:
Local files: 11
Database files: 11
Untracked local files: 0
Untracked database files: 0
Common untracked files: 0
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
Scanning storage files...
12/30/2024, 9:42:05 AM->[HiddenFileSync]  Known/Exist 11/11, Totally 11 files.
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
[Storage hidden file statics]
Known files: 11
Actual files: 11
All files: 11
Offline Changed files: 0
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Storage -> DB ]
Done  
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
Done  
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [Database hidden file statics]
All files: 11
Offline Changed files: 0
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ DB -> Storage ]
Done  
12/30/2024, 9:42:05 AM->[HiddenFileSync]  [⚙ Apply untracked changes ]
Done  
12/30/2024, 9:42:05 AM->[ModuleLiveSyncMain]  Additional safety scan..
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Checking conflicted files
12/30/2024, 9:42:05 AM->Before LiveSync, start OneShot once...
12/30/2024, 9:42:05 AM->OneShot Sync begin... (pullOnly)
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Some files have been left conflicted! Please resolve them by "Pick a file to resolve conflict". The list is written in the log.
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/PLUGIN_DATA/obsidian-livesync.md
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/CONFIG/appearance.json.md
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/CONFIG/workspace.json.md
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/CONFIG/community-plugins.json.md
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/CONFIG/core-plugins.json.md
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/CONFIG/workspace-mobile.json.md
12/30/2024, 9:42:05 AM->[ModuleInteractiveConflictResolver]  Conflicted: ix:minimac/CONFIG/app.json.md
12/30/2024, 9:42:05 AM->[ModuleCheckRemoteSize]  Checking storage sizes
12/30/2024, 9:42:06 AM->[ModuleCheckRemoteSize]  Remote storage size: 311.16MB
12/30/2024, 9:42:06 AM->[ModuleLiveSyncMain]  Additional safety scan completed
12/30/2024, 9:42:06 AM->Replication paused
12/30/2024, 9:42:06 AM->Replication completed
12/30/2024, 9:42:06 AM->LiveSync begin...
12/30/2024, 9:42:06 AM->Replication activated
12/30/2024, 9:42:06 AM->Replication paused
12/30/2024, 9:43:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
Scanning storage files...
12/30/2024, 9:43:05 AM->[HiddenFileSync]  Known/Exist 11/11, Totally 11 files.
12/30/2024, 9:43:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
[Storage hidden file statics]
Known files: 11
Actual files: 11
All files: 11
Offline Changed files: 0
12/30/2024, 9:43:05 AM->[HiddenFileSync]  [⚙ Storage -> DB ]
Done  
12/30/2024, 9:43:05 AM->[HiddenFileSync]  [⚙ Scanning Storage -> DB ]
Done  
```
</details>

### Network log
Network logs displayed in DevTools will possibly help with connection-related issues. To capture that, please refer to [DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools).

### Screenshots
If applicable, please add screenshots to help explain your problem.

![Screenshot 2024-12-30 at 9 31 44 AM](https://github.com/user-attachments/assets/c48334d9-63a8-412e-a4ac-caa9ddce32a2)

![Screenshot 2024-12-30 at 9 35 11 AM](https://github.com/user-attachments/assets/5e1e083b-9eb2-4bbe-993f-379a67c69f84)

### Other information, insights and intuition.
Please provide any additional context or information about the problem.
