### ISSUE TITLE
TypeError:Failed to fetch

### ISSUE THREAD

**Issue by etweisberg** [vrtmrz/obsidian-livesync#574]
## Abstract
After adding some PDFs into my vault this error started appearing when attempting replication. I have tried updating the couchdb image to the latest version, deleting my `obsidiandb` database and re-creating it, and deleting the PDFs from my vault, but the error persists.

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Everything synchronised

## Actually happened
- Synchronisation has been cancelled with the message `TypeError:Failed to fetch`
- Some population of couchdb but replication not completed

## Reproducing procedure

Seemed to occur after including PDFs in my vault

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36
FileSystem: insensitive
---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: 9d251395b39d3f8b3eaef84f7959498d
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.7
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 2539bee14e69cfae
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 2000
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: true
useAdvancedMode: false
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
<!-- paste here -->
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
1/22/2025, 5:59:48 PM->[HiddenFileSync]  Hidden file will skip 0 files
1/22/2025, 5:59:48 PM->Cache initialized 300 / 50000000
1/22/2025, 5:59:49 PM->[ModuleObsidianAPI]  HTTP:POST (36) to:/_changes?style=all_docs&feed=longpoll&heartbeat=30000&filter=_selector&since=1198-g1AAAACReJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5CchzzwWKsaeZWKSYm5mgq8dhQh4LkGRoAFL_EQalQwxKMjM3NDJH15YFAPrOKxQ&limit=25 -> failed
1/22/2025, 5:59:49 PM->AbortError:The user aborted a request.
1/22/2025, 5:59:54 PM->Log window opened
1/22/2025, 6:00:01 PM->OneShot Sync begin... (sync)
1/22/2025, 6:00:01 PM->Looking for the point last synchronized point.
1/22/2025, 6:00:01 PM->Replication activated
1/22/2025, 6:00:01 PM->[ModuleObsidianAPI]  HTTP:POST (2382132) to:/_bulk_docs -> failed
1/22/2025, 6:00:01 PM->TypeError:Failed to fetch
1/22/2025, 6:00:01 PM->Replication error
1/22/2025, 6:00:01 PM->Error:Failed to fetch
1/22/2025, 6:00:01 PM->Replication stopped.
1/22/2025, 6:00:01 PM->Retry with lower batch size:15/15
1/22/2025, 6:00:01 PM->OneShot Sync begin... (sync)
1/22/2025, 6:00:01 PM->Looking for the point last synchronized point.
1/22/2025, 6:00:01 PM->Replication activated
1/22/2025, 6:00:02 PM->↑5 (54) ↓0
1/22/2025, 6:00:02 PM->[ModuleObsidianAPI]  HTTP:POST (2409529) to:/_bulk_docs -> failed
1/22/2025, 6:00:02 PM->TypeError:Failed to fetch
1/22/2025, 6:00:02 PM->Replication error
1/22/2025, 6:00:02 PM->Error:Failed to fetch
1/22/2025, 6:00:02 PM->Replication stopped.
1/22/2025, 6:00:02 PM->Retry with lower batch size:10/10
1/22/2025, 6:00:02 PM->OneShot Sync begin... (sync)
1/22/2025, 6:00:02 PM->Looking for the point last synchronized point.
1/22/2025, 6:00:02 PM->Replication activated
1/22/2025, 6:00:02 PM->[ModuleObsidianAPI]  HTTP:POST (1517747) to:/_bulk_docs -> failed
1/22/2025, 6:00:02 PM->TypeError:Failed to fetch
1/22/2025, 6:00:02 PM->Replication error
1/22/2025, 6:00:02 PM->Error:Failed to fetch
1/22/2025, 6:00:02 PM->Replication stopped.
1/22/2025, 6:00:02 PM->Retry with lower batch size:7/7
1/22/2025, 6:00:02 PM->OneShot Sync begin... (sync)
1/22/2025, 6:00:02 PM->Looking for the point last synchronized point.
1/22/2025, 6:00:02 PM->Replication activated
1/22/2025, 6:00:02 PM->↑7 (45) ↓0
1/22/2025, 6:00:02 PM->[ModuleObsidianAPI]  HTTP:POST (1249290) to:/_bulk_docs -> failed
1/22/2025, 6:00:02 PM->TypeError:Failed to fetch
1/22/2025, 6:00:02 PM->Replication error
1/22/2025, 6:00:02 PM->Error:Failed to fetch
1/22/2025, 6:00:02 PM->Replication stopped.
1/22/2025, 6:00:02 PM->Retry with lower batch size:6/6
1/22/2025, 6:00:02 PM->OneShot Sync begin... (sync)
1/22/2025, 6:00:02 PM->Looking for the point last synchronized point.
1/22/2025, 6:00:02 PM->Replication activated
1/22/2025, 6:00:03 PM->[ModuleObsidianAPI]  HTTP:POST (1070740) to:/_bulk_docs -> failed
1/22/2025, 6:00:03 PM->TypeError:Failed to fetch
1/22/2025, 6:00:03 PM->[ModuleObsidianAPI]  HTTP:POST (36) to:/_changes?style=all_docs&filter=_selector&since=1198-g1AAAACReJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5CchzzwWKsaeZWKSYm5mgq8dhQh4LkGRoAFL_EQalQwxKMjM3NDJH15YFAPrOKxQ&limit=6 -> failed
1/22/2025, 6:00:03 PM->AbortError:The user aborted a request.
1/22/2025, 6:00:03 PM->Replication error
1/22/2025, 6:00:03 PM->Error:Failed to fetch
1/22/2025, 6:00:03 PM->Replication stopped.
1/22/2025, 6:00:03 PM->We can't replicate more lower value.
```
</details>

### Network log
Network logs displayed in DevTools will possibly help with connection-related issues. To capture that, please refer to [DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools).

<img width="609" alt="Image" src="https://github.com/user-attachments/assets/5bc1cb67-77d9-4a21-876a-56d59b0b9c04" />

### Screenshots
See Networking screenshot
