### ISSUE TITLE
livesync stops working on iOS + Windows

### ISSUE THREAD

**Issue by Impure2411** [vrtmrz/obsidian-livesync#578]
## Abstract
Win10 and iOS does not sync anymore after the big update around 6 months ago (I don't remember tbh. I've just left it as it was, and it still does not work so made my mind to report the issue finally.)

## Expected behaviour
- Everything synchronised

## Actually happened
- No files synchronised
- I tried rubuilding everything, but that does not do the trick. Each time I open Obsidian both on Win10 and iOS, it says "Scram enabled", and "Resume and restart Obsidian" does not solve the issue either.

## Reproducing procedure

1. Open Obsidian.
2. Click "rebuild everything
3. Open Obsidian again
4. Click "resume and restart Obsidian

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
<!-- paste here -->
```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
<!-- paste here -->
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
<!-- paste here -->
```
</details>

### Network log
Network logs displayed in DevTools will possibly help with connection-related issues. To capture that, please refer to [DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools).

### Screenshots
![Image](https://github.com/user-attachments/assets/aca356dd-f03a-450e-9911-2b2239886aeb)
![Image](https://github.com/user-attachments/assets/daca1139-9ff9-4dea-8a41-bd73db9a1039)

### Other information, insights and intuition.
I'm wondering if it's because I'm using Obsidian Git plugin, which is a problem a user reported [on the other issue](https://github.com/vrtmrz/obsidian-livesync/issues/517). Although my vault is around 44MB and does not much use plugins, it's almost 1.7GB for livesync.

**Comment by vrtmrz** [comment]
Apologies for my absence! And, also sorry for your inconvenience.

The log indicates that there are over 4000 files in your vault. Do they indeed exist?
I have not looked at your configuration, so I am not sure yet, but if you have `Hidden file sync` enabled and `Ignore patterns` doesn't contain `/.git/`, maybe your device trying to sync a lot of files.

![Image](https://github.com/user-attachments/assets/770c0aa5-0629-4577-b351-2b3d93af8dad)

And, we can disable the scram mode manually. May I ask you to check what happens If you have disabled these toggles?

![Image](https://github.com/user-attachments/assets/d0d48af3-a23c-4e00-9a85-0d9e5b509b68)

I would like you to share your log and report with me for more information. Thank you for your cooperation in advance!

**Comment by Impure2411** [comment]
Thanks for the reply! Yes, my files exceed 4000.

Just checked the ignore pattern and scram switches, and they are like these.
![Image](https://github.com/user-attachments/assets/312ecc11-4f3c-4d6f-8d0b-298c8a717e34)

![Image](https://github.com/user-attachments/assets/b65a2ac0-4637-49fa-87a5-abbebc3f31d7)

### Report from the LiveSync
<details>
<summary>Report from hatch</summary>

```

---- Obsidian info ----
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.8.7 Chrome/130.0.6723.191 Electron/33.3.2 Safari/537.36
FileSystem: insensitive
---- remote config ----
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.15
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: PC-main
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: 2c7634d6b1ad0e90
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 333
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 1801
usePluginSyncV2: false
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: true
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
useV1: true
configPassphrase: ""
preset: ""
syncMode: ONEVENTS
dummy: 0
```
