### ISSUE TITLE
Could not connect to [myurl/db-name]:TypError:Failed to fetch

### ISSUE THREAD

**Issue by mahoromax** [vrtmrz/obsidian-livesync#611]
## Abstract
After setting up my own live-sync server (CouchDB in docker, Cloudflared Tunnel) and creating the configuration the plugin fails to connect to the server with the error:
> Could not connect to [myurl/db-name]:TypError:Failed to fetch **Note ** This error caused by many reasons. The only sure thing is you didn't touch the server. [...]

I can manually access the CouchDB via that URL without issues (and over https)

## Expected behaviour
Connect to the server

## Reproducing procedure
1. Configuration via readme / linked manuals
2. Setup with URI and wizard
3. Error after building local DB
4. Error each time the "Test Database Configuration" is activated.

### Report from the LiveSync

<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.7.7 Chrome/128.0.6613.186 Electron/32.2.5 Safari/537.36
FileSystem: insensitive
---- remote config ----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  methods: GET, PUT, POST, HEAD, DELETE
  origins: https://obsidiansync.mhmx.top
chttpd:
  bind_address: any
  enable_cors: "true"
  port: "5984"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  secret: 6c8d4580398f4720db3a1aefa03af004
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  bind_address: 127.0.0.1
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.19
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 50
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: b0ccdcc933aac890
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 100
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 800
usePluginSyncV2: false
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: false
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
doctorProcessedVersion: 0.24.16
configPassphrase: ""
preset: ""
syncMode: PERIODIC
dummy: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

Checking the DevTools / Inspector I found mostly 2 types of errors:

1.
```
Access to fetch at 'https://[myurl]/[db-name]/' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
``` 
2.
```
plugin:obsidian-livesync:42 
 GET https://[myurl]/[db-name]/ net::ERR_FAILED
fetch	@	plugin:obsidian-livesync:42
ourFetch	@	plugin:obsidian-livesync:6
fetchJSON	@	plugin:obsidian-livesync:6
setup2	@	plugin:obsidian-livesync:6
HttpPouch.api._info	@	plugin:obsidian-livesync:6
eval	@	plugin:obsidian-livesync:42
eval	@	plugin:obsidian-livesync:6
eval	@	plugin:obsidian-livesync:6
eval	@	plugin:obsidian-livesync:6
eval	@	plugin:obsidian-livesync:6
execute	@	plugin:obsidian-livesync:42
ready	@	plugin:obsidian-livesync:42
eval	@	plugin:obsidian-livesync:42
eval	@	plugin:obsidian-livesync:6
```

</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```

[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->[HiddenFileSync]  Hidden file will skip 0 files
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->P2P is not enabled
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->Cache initialized 300 / 50000000
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->OneShot Sync begin... (sync)
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->[ModuleObsidianAPI]  HTTP:GET to:/ -> failed
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->Could not connect to https://[my-url]/[db-name]:TypeError:Failed to fetch
**Note** This error caused by many reasons. The only sure thing is you didn't touch the server.
To check details, open inspector.
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:43:51->Could not connect to server.
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->[ModuleObsidianAPI]  HTTP:GET to:/ -> failed
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->Could not connect to https://[my-url] : [db-name] 
(TypeError:Failed to fetch
**Note** This error caused by many reasons. The only sure thing is you didn't touch the server.
To check details, open inspector.)
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->[ModuleObsidianAPI]  HTTP:GET to:/ -> failed
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:23->Could not connect to https://[my-url]/[db-name]:TypeError:Failed to fetch
**Note** This error caused by many reasons. The only sure thing is you didn't touch the server.
To check details, open inspector.
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->OneShot Sync begin... (sync)
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->[ModuleObsidianAPI]  HTTP:GET to:/ -> failed
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->TypeError:Failed to fetch
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->Could not connect to https://[my-url]/[db-name]:TypeError:Failed to fetch
**Note** This error caused by many reasons. The only sure thing is you didn't touch the server.
To check details, open inspector.
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->Could not connect to server.
[vault-name]-b0ccdcc933aac890:22.3.2025, 14:44:48->[ModuleConflictResolver]  [conflict] Not conflicted or cancelled: livesync_log_2025-03-22.md

```
</details>

### Network log
<details>
<summary>Network log</summary>
Found this in addition to the console tab:
```
TypeError: Failed to fetch
    at fetch (plugin:obsidian-livesync:42:1181350)
    at ourFetch (plugin:obsidian-livesync:6:329678)
    at fetchJSON (plugin:obsidian-livesync:6:327176)
    at setup2 (plugin:obsidian-livesync:6:327660)
    at HttpPouch.api._info (plugin:obsidian-livesync:6:331927)
    at klass.eval (plugin:obsidian-livesync:42:1126844)
    at klass.eval (plugin:obsidian-livesync:6:224194)
    at eval (plugin:obsidian-livesync:6:223232)
    at new Promise (<anonymous>)
    at klass.eval (plugin:obsidian-livesync:6:223070)
```
</details>

### Other information, insights and intuition.
>Has been blocked by CORS policy

This makes me believe that there is something missing in the couchDB configuration. In the Fauxton interface there are a few options mentioning CORS, but none about headers.

> No 'Access-Control-Allow-Origin' header is present on the requested resource

so we're missing something in the answer - but I have no idea whether this would be added from CouchDB or Cloudflared?
