### ISSUE TITLE
CORS Issues when hosting through Zoraxy Proxy

### ISSUE THREAD

**Issue by MulverineX** [vrtmrz/obsidian-livesync#638]
## Abstract
Attempted to host the livesync docker container and access through Zoraxy. 

## Expected behaviour
- Synchronization works without a problem

## Actually happened
- Synchronisation spams notifications & console with Native Fetch errors pertaining to CORS OPTIONS requests from chromium failing to resolve properly 
- No files synchronised

## Reproducing procedure

1. Configure LiveSync as in the attached material.
2. Added HTTP Proxy entry to Zoraxy with a valid Authorization server bound header & basic auth configured. Also tried adding `Access-Control-Allow-Origin` `*` to the client bound header overrides as well. 
2. Click the replication button on the ribbon.
3. Synchronising has begun.
4. About two or three seconds later, we got the error `TypeError ... `.
5. Replication has been stopped. No files synchronised. 

### Screenshots
![IMG_20250502_151805_855.jpg](https://github.com/user-attachments/assets/fdc6a315-63cb-4834-a5aa-1229115df6ca)

Latest versions of all involved software. Latest Debian 12 Server with CasaOS as my docker server manager, I installed the Obsidian LiveSync docker container through the provided config in the stock CasaOS apps directory. 

Loading the requested link manually in the browser in its own tab works after entering username/password.

Tried setting `*` to `app://obsidian.md` and that didn't work either.

Would rather not switch to Nginx Proxy Manager or use a different port. 

### Docker config (exported from CasaOS)
<details>
  <summary>Obsidian Livesync</summary>
  
```yaml
  name: big-bear-obsidian-livesync
  services:
    app:
      cpu_shares: 90
      command: []
      container_name: obsidian-livesync
      deploy:
        resources:
          limits:
            memory: 7785M
      environment:
        - COUCHDB_PASSWORD=casaos
        - COUCHDB_USER=casaos
      hostname: obsidian-livesync
      image: couchdb:3.4.3
      labels:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/obsidian.png
      ports:
        - mode: ingress
          target: 5984
          published: "5984"
          protocol: tcp
      restart: unless-stopped
      volumes:
        - type: bind
          source: /charis/host/volumes/obsidian-livesync-db
          target: /opt/couchdb/data
          bind:
            create_host_path: true
        - type: bind
          source: /charis/host/config/obsidian-livesync.ini
          target: /opt/couchdb/etc/local.ini
          bind:
            create_host_path: true
      x-casaos:
        ports:
          - container: "5984"
            description:
              en_us: "Container Port: 5984"
        volumes:
          - container: /opt/couchdb/data
            description:
              en_us: "Container Path: /opt/couchdb/data"
          - container: /opt/couchdb/etc/local.ini
            description:
              en_us: "Container Path: /opt/couchdb/etc/local.ini"
      devices: []
      cap_add: []
      networks:
        - default
      privileged: false
  networks:
    default:
      name: big-bear-obsidian-livesync_default
  x-casaos:
    architectures:
      - amd64
      - arm64
    author: BigBearTechWorld
    category: BigBearCasaOS
    description:
      en_us: Self-hosted database for synchronizing Obsidian vaults.
    developer: ""
    hostname: ""
    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/obsidian.png
    index: /
    is_uncontrolled: false
    main: app
    port_map: "5984"
    scheme: http
    store_app_id: big-bear-obsidian-livesync
    tagline:
      en_us: Self-hosted database for synchronizing Obsidian vaults.
    thumbnail: ""
    tips:
      before_install:
        en_us: >
          Run this script before installing the big-bear-obsidian-livesync
          application:
          ```
          bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-obsidian-livesync-local-ini/run.sh)"
          ```
          After running this script, you need to restart the container.
    title:
      custom: ""
      en_us: Obsidian Livesync
```
  
</details>
