### ISSUE TITLE
Error on processing job on clerk (no sync)

### ISSUE THREAD

**Issue by Kuuh4** [vrtmrz/obsidian-livesync#641]
Thank you for taking the time to report this issue!
To improve the process, I would like to ask you to let me know the information in advance.

All instructions and examples, and empty entries can be deleted.
Just for your information, a [filled example](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Issue+example) is also written.

## Abstract
The synchronisation doesn't work when initialized 

## Expected behaviour
- Synchronisation ends with the message `Replication completed`
- Everything synchronised

## Actually happened
- Synchronisation has been cancelled with the message `Error on processing job on clerk ` (captured in the attached log, around last two lines)
- No files synchronised

## Reproducing procedure

1. Configure LiveSync as in the attached material.
2. Click the replication button on the ribbon.
3. Synchronising has begun.
4. About two or three seconds later, we got the error `Error on processing job on clerk ... `.
5. Replication has been stopped. No files synchronised.

Note: If you do not catch the reproducing procedure, please let me know the frequency and signs.

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
<!-- paste here -->
---- Obsidian info ----
Navigator: Mozilla/5.0 (Linux; Android 14; SM-X810 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/135.0.7049.111 Safari/537.36
FileSystem: sensitive
---- remote config ----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /e=_/_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.25
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTP)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: false
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: tablet
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
usePluginSync: true
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: true
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/, ^\.git\/, \/workspace$, \/workspace.json$, \/workspace-mobile.json$
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: /storage/emulated/0/Obsidian/Awesome_Vault
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: ""
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 2000
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: true
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: true
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
P2P_AutoAcceptingPeers: ""
P2P_AutoDenyingPeers: ""
P2P_IsHeadless: false
doctorProcessedVersion: 0.24.16
bucketCustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
couchDB_CustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
useJWT: false
jwtAlgorithm: ""
jwtKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtKid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtSub: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtExpDuration: 5
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
<!-- paste here -->
SYSTEM INFO:
	Operating system: android 14 (samsung SM-X810)
	Obsidian version: 1.8.10 (197)
	API version: v1.8.10
	Login status: not logged in
	Language: en
	Live preview: on
	Base theme: adapt to system
	Community theme: AnuPpuccin v1.5.0
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 7
		1: Self-hosted LiveSync v0.24.25
		2: Custom Font Loader v1.6.0
		3: Dataview v0.5.68
		4: Homepage v4.2
		5: Minimal Theme Settings v8.1.1
		6: Style Settings v1.0.9
		7: Typewriter Mode v1.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
<!-- paste here -->
08/05/2025, 14:01:27->[ModuleLiveSyncMain]  Loading plugin...
08/05/2025, 14:01:27->[ModuleLiveSyncMain]  Self-hosted LiveSync v0.24.25 0.24.25
08/05/2025, 14:01:27->[HiddenFileSync]  Hidden file will skip 0 files
08/05/2025, 14:01:27->[ModuleLocalDatabaseObsidian]  Waiting for ready...
08/05/2025, 14:01:27->Opening Database...
08/05/2025, 14:01:27->Database is now ready.
08/05/2025, 14:01:33->[ModuleInitializerFile]  Initialize and checking database files
08/05/2025, 14:01:33->[ModuleInitializerFile]  Checking deleted files
08/05/2025, 14:01:33->[ModuleInitializerFile]  Collecting local files on the DB: 25
08/05/2025, 14:01:33->[ModuleInitializerFile]  Collecting local files on the DB: 50
08/05/2025, 14:01:33->[ModuleInitializerFile]  Collecting local files on the DB: 75
08/05/2025, 14:01:33->[ModuleInitializerFile]  Collecting local files on the DB: 100
08/05/2025, 14:01:33->[ModuleInitializerFile]  Collecting local files on the DB: 125
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 150
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 175
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 200
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 225
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 250
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 275
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 300
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 325
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 350
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 375
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 400
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 425
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 450
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 475
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 500
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 525
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 550
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 575
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 600
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 625
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 650
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 675
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 700
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 725
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 750
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 775
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 800
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 825
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 850
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 875
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 900
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 925
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 950
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 975
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1000
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1025
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1050
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1075
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1100
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1125
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1150
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1175
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1200
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1225
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1250
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1275
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1300
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1325
08/05/2025, 14:01:34->[ModuleInitializerFile]  Collecting local files on the DB: 1350
08/05/2025, 14:01:34->[ModuleInitializerFile]  Synchronising...
08/05/2025, 14:01:34->[ModuleInitializerFile]  UPDATE DATABASE: Nothing to do
08/05/2025, 14:01:34->[ModuleInitializerFile]  UPDATE STORAGE
08/05/2025, 14:01:34->[ModuleInitializerFile]  SYNC DATABASE AND STORAGE
08/05/2025, 14:01:34->[ModuleInitializerFile]  UPDATE STORAGE: DONE:1, FAILED:0, LAST:1068
08/05/2025, 14:01:34->[ModuleInitializerFile]  STORAGE <- DB :Aulas 2025.1/Ética Cristã - CRE1241 - 7TC/2025-05-05 Aula.md
08/05/2025, 14:01:34->[ModuleInitializerFile]  STORAGE -> DB :Daily_Notes/2025-05-08.md
08/05/2025, 14:01:34->[ModuleInitializerFile]  UPDATE STORAGE: DONE:1067, FAILED:0, LAST:2
08/05/2025, 14:01:34->Chunks saved: doc: Daily_Notes/2025-05-08.md ,chunks: 15 (new:1, recycled:1, cached:13)
08/05/2025, 14:01:34->[ModuleDatabaseFileAccess]  STORAGE -> DB (plain) Daily_Notes/2025-05-08.md
08/05/2025, 14:01:34->[ModuleInitializerFile]  UPDATE STORAGE: DONE:1067, FAILED:0, LAST:2
SYNC DATABASE AND STORAGE: DONE:283, FAILED:0, LAST:1
08/05/2025, 14:01:34->Error on processing job on clerk
08/05/2025, 14:01:45->Log window opened
```
</details>

### Network log
Network logs displayed in DevTools will possibly help with connection-related issues. To capture that, please refer to [DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools).

No requests in red.

<details>

![Image](https://github.com/user-attachments/assets/03cab38b-d88f-417b-abf3-77774e87b7d3)

</details>

### Other information, insights and intuition.
I use 3 devices (windows and 2 android). When this first happened, I managed to get around it by refetching all from the database. It's only a temporary fix, as it comes back in a few sessions.
