### ISSUE TITLE
AbortError:Version change transaction was aborted in upgradeneeded event handler.

### ISSUE THREAD

**Issue by kbaniszack** [vrtmrz/obsidian-livesync#649]
## Abstract
Synchronization fails intermittently. It starts normally but gets interrupted with replication-related errors (Replication error, AbortError, InvalidStateError, etc.).

## Expected behaviour
- Synchronization completes with the message Replication completed
- All files are synchronized successfully

## Actually happened
- Synchronization starts (OneShot Sync begin...) but ends prematurely with:
   - Replication error
   - InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
   - AbortError: Version change transaction was aborted in upgradeneeded event handler.
- No files synchronised
- The error occurs randomly without any specific trigger

## Reproducing procedure

There’s no clear reproduction procedure, but the issue occurs frequently. Here’s what I observed:
1. LiveSync is configured with a self-hosted CouchDB instance
2. Synchronization starts either on launch or manually
3. A few seconds later, it fails with the above errors
4. Occasionally, sync works for a while before failing again

### Frequency 
- Random but recurrent (multiple times per day)

### Report from the LiveSync

<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (Linux; Android 13; TFY-LX1 Build/HONORTFY-L31CQ; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.61 Mobile Safari/537.36
FileSystem: sensitive
---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: a4aaf74c042b7e731e5431ac9e6f8d82
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.26
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: true
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: Mobile
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
hideFileWarningNotice: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesTargetPatterns: ""
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: /storage/emulated/0/Documents/obsidian
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: Pièces jointes_
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: false
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: true
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 40
minimumIntervalOfReadChunksOnline: 50
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 100
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(8 letters)
endpoint: self-hosted?((HTTPS))
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: def
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 0
usePluginSyncV2: false
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: true
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: true
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
P2P_AutoAcceptingPeers: ""
P2P_AutoDenyingPeers: ""
P2P_IsHeadless: false
doctorProcessedVersion: 0.24.16
bucketCustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
couchDB_CustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
useJWT: false
jwtAlgorithm: ""
jwtKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtKid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtSub: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtExpDuration: 5
useRequestAPI: false
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0
```
</details>

### Plug-in log

<details>
<summary>Plug-in log</summary>

```
26/05/2025 09:43:47->Before LiveSync, start OneShot once...
26/05/2025 09:43:47->OneShot Sync begin... (pullOnly)
26/05/2025 09:43:48->Replication activated
26/05/2025 09:43:49->Replication error
26/05/2025 09:43:49->Error:
26/05/2025 09:43:49->Replication stopped.
26/05/2025 09:43:49->Replication error
26/05/2025 09:43:49->Error:
26/05/2025 09:44:13->[ModuleReplicator]: Every handler for $everyBeforeReplicate failed
26/05/2025 09:44:13->InvalidStateError:Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
26/05/2025 09:44:13->AbortError:Version change transaction was aborted in upgradeneeded event handler.
26/05/2025 09:44:13->OneShot Sync begin... (sync)
26/05/2025 10:00:01->AbortError:Version change transaction was aborted in upgradeneeded event handler.
26/05/2025 10:00:01->Before LiveSync, start OneShot once...
26/05/2025 10:00:01->OneShot Sync begin... (pullOnly)
26/05/2025 10:01:06->AbortError:Version change transaction was aborted in upgradeneeded event handler.
26/05/2025 10:01:06->Before LiveSync, start OneShot once...
26/05/2025 10:01:06->OneShot Sync begin... (pullOnly)
```
</details>

## Note : 
Obsidian seems to re-index the vault quite frequently on startup or during usage, which might interfere with LiveSync operations.
