### ISSUE TITLE
self-hosted live sync not syncing

### ISSUE THREAD

**Issue by leon-thomm** [vrtmrz/obsidian-livesync#660]
I have a CouchDB running behind a public IP on my own server using docker, and it seems to be working fine. After completing the remote configuration (with successful `Check`) and clicking on `Fetch`, I see notifications:
```
Remote database is newer or corrupted, make sure to latest version of self-hosted-livesync installed
```
it even shows this when I purge the database and start a new instance
```
Failed to get the preferred tweak values from the server.
```
I see no errors in the CouchDB output. When I then proceed anyway and try to find any issues in the `Hatch` menu (`Run Doctor`, `Recreate All`, `Resolve All`, `Verify All`), I cannot find any issues. Nevertheless, it does not synchronize, as I can verify using multiple devices/vaults. Even when I use the setup URI from one device to set up the other, the documents won't synchronize. Also, the plugin changes my Sync Mode to `on events` all the time, even though I manually set it to `LiveSync`. What should I do?
```
---- Obsidian info ----
Navigator: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.8.10 Chrome/134.0.6998.205 Electron/35.5.0 Safari/537.36
FileSystem: sensitive
---- remote config ----
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.28
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTP)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
hideFileWarningNotice: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesTargetPatterns: ""
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: dfef7a02c0f886c7
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 30
minimumIntervalOfReadChunksOnline: 25
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: def
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 2000
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: true
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: true
useAdvancedMode: false
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(9 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(13 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
P2P_AutoAcceptingPeers: ""
P2P_AutoDenyingPeers: ""
P2P_IsHeadless: false
doctorProcessedVersion: ""
bucketCustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
couchDB_CustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
useJWT: false
jwtAlgorithm: ""
jwtKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtKid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtSub: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtExpDuration: 5
useRequestAPI: false
bucketPrefix: ""
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0
```

**Comment by leon-thomm** [comment]
One issue seems to be the database generated by the plugin when no database name is given. It is always reported to be corrupted right afterwards, which is not the case when I generate an empty database and use that.

Unfortunately, I am still running into tons of database corruption issues. I am also fighting with various UI bugs where

* I generally need to restart Obsidian multiple times and set synchronization back to LiveSync every single time
* sometimes I need to click on dialog buttons to set setting in order for them to be persistent, sometimes I need to discard the dialog and manually configure options
* sometimes it gives me a button to resolve conflicts but whatever is behind the button then suddenly breaks
* sometimes it locks the remote database and I cannot unlock it even though all the testing tools report no issues

it's really too much to report at the moment

**Comment by alextremblay** [comment]
Hi @vrtmrz I've arrived at this issue because i also started getting `Remote database is newer or corrupted, make sure to latest version of self-hosted-livesync installed` and `Failed to get the preferred tweak values from the server.` errors after updating from a (very old, don't remember version number, sometime in 2024) version of the plugin to v0.25.61

I have tried every recommendation made by you in this issue, and have even gone as far as to build a completely new fly.io couchdb server instance using your [very cool notebook!](https://github.com/vrtmrz/obsidian-livesync/blob/main/setup-flyio-on-the-fly-v2.ipynb)
and reinstalling livesync and reconfiguring it using the setup uri produced by that notebook. I'm still getting `Failed to get the preferred tweak values from the server.`  errors during setup when i get to the stage where the livesync plugin prompts me to rebuild the server database using the contents of this device. I can confirm that the new couchdb instance contains 5mb of... *something*, but when i use that same setup uri to join another device, it also gets the `Failed to get the preferred tweak values from the server.` error and continually prompts me to retry

if i cancel the retry, i can see that the new device does not contain any of my obsidian notes.

At this point I'm stuck. Livesync was working perfectly for me until i updated to the latest version, and now i have no way to get back to a working installation. 
What is my next step here? How can i assist you in troubleshooting this issue?

**Comment by vrtmrz** [comment]
Thank you for opening the issue!
I am still investigating this issue; however, it may have occurred during pre-replication checking. Anyway, this has been reproduced now.
Could you please open the connection settings via the 🔧 icon and click `Test Settings and Continue`? It may test the settings and initialise if needed.

I will look into the root cause, but please give this a try first! Sorry for the inconvenience!

**Comment by vrtmrz** [comment]
@alextremblay Thank you so much for your patience!
This issue has been fixed at v0.25.62. 
Would you mind if I asked you to check the behaviour, please? 
If you have already fixed by the workaround, please check that this release is harmless and close this issue, please.

**Comment by alextremblay** [comment]
Hi @vrtmrz I DID find a workaround for this...  

I originally tried pressing the `Reset > Delete local database to reset or uninstall Self-hosted LiveSync > Delete` button in the last tab of the plugin's UI and then reconfiguring the plugin using my newly-generated Setup URI, but that didn't work.

The workaround was to press the `Reset > Discard existing settings and databases > Discard` button in the second tab of the plugin's UI and then reconfiguring the plugin using my newly-generated Setup URI

Would it be possible to change / update the labelling of these two buttons? The one in the "Setup" tab does exactly what i expect it to, the one in the last tab of the UI does not seem to do anything that I can see / notice

**Comment by alextremblay** [comment]
I have updated to v0.25.62 and now what i'm seeing is that content is no longer being synced.

I've made changes to a document, and saw the livesync widget on the corner change, looks like it uploaded *something* to the server, but with my other obsidian instance open on my other machine, no changes appeared, even after restarting obsidian

i also tried the "LiveSync: Replicate Now" command, and opened the log. the last two entries in the log are "Replication Activated" and "Replication completed"

I also noticed further back in the log an entry like "usePluginSyncV2 is false but should be true"
I went back into the sync settings, and applied the "LiveSync" preset. the whole ui of that tab changed and now it just says "Sync Mode" is set to "LiveSync"

i then went back to the document and ran the "Replicate Now" command. The livesync widget on the corner of the screen show 5 next to the up arrow, 0 next to the down arrow, and the message "Replication is already in progress"

**Comment by alextremblay** [comment]
I've fully closed and re-opened obsidian, livesync did a bunch of stuff, and the last line in the log now reads "LiveSync begin..."

i've left it for a couple minutes, and it still hasn't changed from this state

**Comment by vrtmrz** [comment]
Oh my goodness, I am sorry to have put you through all that trouble.
Right then, would you mind if i I asked you to share the report with me again, please? You can create reports using Hatc's 'Copy report to clipboard' feature. 

So, I would love to check whether any unintended settings are having an effect.

**Comment by alextremblay** [comment]
Sure, here you go. Thanks for looking into it!

```
# ---- Obsidian info ----
navigator: Mozilla/5.0 (Linux; Android 16; Pixel 6 Pro Build/CP1A.260305.018; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/147.0.7727.137 Mobile Safari/537.36
fileSystem: sensitive

---
# ---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---
# ---- Plug-in config ----
version: 0.25.62
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
hideFileWarningNotice: false
networkWarningStyle: ""
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 50
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesTargetPatterns: ""
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: /storage/emulated/0/Documents/Personal
ignoreVersionCheck: false
lastReadUpdates: 25
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 50
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
remoteConfigurations:
  legacy-couchdb:
    id: legacy-couchdb
    name: CouchDB Remote
    uri: sls+https://
    isEncrypted: false
activeConfigurationId: legacy-couchdb
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 100
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: def
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 2000
usePluginSyncV2: false
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: false
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: false
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(12 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(8 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
P2P_AutoAcceptingPeers: ""
P2P_AutoDenyingPeers: ""
P2P_IsHeadless: false
P2P_DevicePeerName: ""
P2P_turnServers: (1 servers configured)
P2P_turnUsername: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_turnCredential: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
doctorProcessedVersion: 0.25.27
bucketCustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
couchDB_CustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
useJWT: false
jwtAlgorithm: ""
jwtKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtKid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtSub: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtExpDuration: 5
useRequestAPI: false
bucketPrefix: ""
chunkSplitterVersion: v3-rabin-karp
E2EEAlgorithm: v2
processSizeMismatchedFiles: false
forcePathStyle: true
syncInternalFileOverwritePatterns: ""
useOnlyLocalChunk: false
maxMTimeForReflectEvents: 0
```
