### ISSUE TITLE
Obsidian Freezes/Stutters when Creating Files/Folders with LiveSync Enabled (Regression from 0.24.28)

### ISSUE THREAD

**Issue by bannert1337** [vrtmrz/obsidian-livesync#669]
## Abstract
Obsidian freezes or stutters for a short duration (1 second or more) when creating new files or folders, or sometimes when opening or clicking on anything, while the Self-hosted LiveSync plugin is enabled. Disabling the plugin resolves these delays entirely. This issue seems to be a regression, as I previously resolved similar behavior by enabling "Batch Update," a feature that was removed in version `0.24.28`.

## Expected behaviour
- Creating new files/folders, opening files, or clicking elements within Obsidian should be instantaneous and not cause any UI freezes or stutters.
- Obsidian should remain responsive with LiveSync enabled.

## Actually happened
- When creating a new file or folder, Obsidian freezes/stutters for approximately 1 second. This delay can vary, sometimes being shorter, sometimes longer.
- Similar intermittent freezes/stutters can occur when opening existing files or clicking various UI elements.
- The issue is consistently reproducible across two different machines (AMD Ryzen 7 5850U on CachyOS, and AMD Ryzen 5 5600H on Windows 11).
- Disabling the Self-hosted LiveSync plugin immediately resolves all observed delays and freezes.

## Reproducing procedure

1. Ensure the Self-hosted LiveSync plugin is enabled and configured (see "Report materials" for configuration details).
2. Open Obsidian.
3. In the file explorer, create a new folder.
4. Observe a short freeze/stutter in Obsidian's UI.
5. Create a new Markdown file within the vault.
6. Observe another short freeze/stutter.
7. Repeat the process multiple times to confirm consistency.
8. (Optional) Disable the LiveSync plugin and repeat steps 3-6 to confirm the absence of freezes.

Note: This issue happens consistently when creating new files or folders. The freezes during opening or clicking are less frequent but still occur.

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
---- Obsidian info ----
Navigator: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.8.10 Chrome/132.0.6834.210 Electron/34.5.8 Safari/537.36
FileSystem: sensitive
---- remote config ----
cluster:
  n: "1"
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: 0.0.0.0
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: b3764d5c802368a5a2d7e0a100c0e11b
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
version:0.24.29
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: true
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: false
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ThinkPad T14
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: false
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
hideFileWarningNotice: false
usePluginSync: true
autoSweepPlugins: true
autoSweepPluginsPeriodic: true
notifyPluginOrSettingUpdated: true
checkIntegrityOnSave: false
batch_size: 25
batches_limit: 25
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: true
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/, ^\.git\/
syncInternalFilesTargetPatterns: ""
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: b226422ef25de0b9
ignoreVersionCheck: false
lastReadUpdates: 24
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 0
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 40
minimumIntervalOfReadChunksOnline: 50
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: livesync
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: def
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 0
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: true
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: true
usePowerUserMode: true
useEdgeCaseMode: true
enableDebugTools: false
suppressNotifyHiddenFilesChange: true
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
P2P_AutoAcceptingPeers: ""
P2P_AutoDenyingPeers: ""
P2P_IsHeadless: false
doctorProcessedVersion: 0.24.16
bucketCustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
couchDB_CustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
useJWT: false
jwtAlgorithm: ""
jwtKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtKid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtSub: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtExpDuration: 5
useRequestAPI: false
bucketPrefix: ""
configPassphrase: ""
preset: ""
syncMode: LIVESYNC
dummy: 0

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
SYSTEM INFO:
	Obsidian version: v1.8.10
	Installer version: v1.8.10
	Operating system: #1 SMP PREEMPT_DYNAMIC Tue, 24 Jun 2025 16:15:18 +0000 6.15.3-3-cachyos
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.6.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 42
	Plugins enabled: 19
		1: Editing Toolbar v3.1.16
		2: Task Genius v9.0.6
		3: Dynamic Outline v1.19.0
		4: Slash Commander v0.3.7
		5: Iconize v2.14.7
		6: Lazy Plugin Loader v1.0.21
		7: Templater v2.12.1
		8: Rollover Daily Todos v1.2.0
		9: Admonition v10.3.2
		10: LanguageTool v1.2.0
		11: Linter v1.29.0
		12: Omnisearch v1.27.1
		13: Self-hosted LiveSync v0.24.29
		14: Differential ZIP Backup v0.0.14
		15: Janitor v1.1.1
		16: Obsifetch v1.3.2
		17: Paperless v0.1.6
		18: Plugin Update Tracker v1.7.0
		19: Terminal v3.19.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
<!-- Please attach the plugin log here, especially a log captured during the freeze event with Verbose Log enabled. -->
```
</details>

### Network log
Network logs displayed in DevTools will possibly help with connection-related issues. To capture that, please refer to [DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools).

### Screenshots
If applicable, please add screenshots to help explain your problem.

Customization Sync settings:
![Customization Sync settings](https://i.imgur.com/your_image_link_here.png)

(Note: Please replace `https://i.imgur.com/your_image_link_here.png` with the actual link to your image if uploaded.)

### Other information, insights and intuition.
- I am currently using Obsidian Self-hosted LiveSync with CouchDB. However, the issue also occurred when I was using S3.
- My `Sync mode` is set to `LiveSync`.
- `Use the trash bin` is enabled.
- The `Filename` of `Sync Settings via Markdown` is set to `livesync`.
- `Hidden file synchronization` is enabled.
- Clicking `Run Doctor` in the LiveSync settings shows `No Issues detected!`.
- The "Batch Update" option, which previously mitigated this issue for me, was removed in LiveSync version `0.24.28` with the note "to avoid unexpected behaviour". My intuition is that the current behavior might be related to the underlying issues or changes that led to the removal of this feature.
- This occurs on both my AMD Ryzen 7 5850U laptop running latest CachyOS and my AMD Ryzen 5 5600H laptop running Windows 11, suggesting it's not specific to a particular OS or hardware brand.
